### ISSUE TITLE
IR: How do I create a level 3 header?

### ISSUE THREAD

**Issue by sergeyshushlyapin** [picklesdoc/pickles#187]
In order to create a level 3 header in Markdown symbols `###` should be used at the start of a line:

```### That is my level 3 header```

But Specflow comments lines started from `#` so there is no header displayed in result. Is there any other way to render the level 3 header in PicklesDoc?

http://stackoverflow.com/questions/28115639/picklesdoc-how-do-i-create-a-level-3-header

**Comment by dirkrombauts** [comment]
Hi,

Unfortunately, the "#" signs are swallowed by the SpecFlow/gherkin parser, so they are never passed to the Markdown parser. So there is - as far as I know - no way to create a level 3 header.

I am in the process of evaluating the upcoming Gherkin3 parser, maybe that parser will behave "better" in this regard.

**Comment by sergeyshushlyapin** [comment]
Ok, clear. Thanks for the quick reply.
