### ISSUE TITLE
Tables in background for Word & Excel

### ISSUE THREAD

**Issue by bzquan** [picklesdoc/pickles#191]
It seems that tables in feature background could not be generated for Word & Excel documents.
Could you double check it?

**Comment by dirkrombauts** [comment]
Hi,

Thanks for bringing this to our attention! Unfortunately my "spare" time is extremely limited now (for the next two or three weeks). So I am currently able to investigate this issue.

Please be patient for a while - and should you find any other things, feel free to open additional issues!

br,
Dirk

**Comment by bzquan** [comment]
Think you for your quick feedbak.
2015/03/02 14:33 "Dirk Rombauts" <notifications@github.com>:

**Comment by mkeCharlie** [comment]
Excel is a little tricker, because it doesn't seem to be rendering the Background at all, whereas Word was rendering it, except for the tables.

**Comment by mkeCharlie** [comment]
Okay, got the Excel version working too. Was actually easier, because of existing test coverage.

**Comment by dirkrombauts** [comment]
Great. I will try to review the push request as soon as possible!
