### ISSUE TITLE
Abbreviations displayed incorrectly with spaces between letters

### ISSUE THREAD

**Issue by sergeyshushlyapin** [picklesdoc/pickles#192]
When I create a feature folder that contains an abbreviation in the name, it looks ok in the solution explorer:
![image](https://cloud.githubusercontent.com/assets/4719165/6483265/acb04146-c277-11e4-9795-7c6d97fa537f.png)

but it looks pretty strange in the menu:
![image](https://cloud.githubusercontent.com/assets/4719165/6483323/46647bcc-c278-11e4-86e1-f9615526d8a7.png)

There are some real spaces between the letters which should no be there. Could you please make it look like this:
![image](https://cloud.githubusercontent.com/assets/4719165/6483380/d655f832-c278-11e4-94ee-3d13645458cb.png)

Thanks!

**Comment by dirkrombauts** [comment]
Hi,

Thanks for bringing this to our attention! Unfortunately my "spare" time is extremely limited now (for the next two or three weeks). So I am currently unable to investigate this issue.

Please be patient for a while - and should you find any other things, feel free to open additional issues!

If you want to fix it yourself: we currently do the string manipulation that is responsible for "A P I" by hand, and I've been meaning to replace that code with Humanizer (https://github.com/MehdiK/Humanizer).

br,
Dirk

**Comment by dirkrombauts** [comment]
Closed by #197

**Comment by dirkrombauts** [comment]
Released as part of version 1.1.0: https://github.com/picklesdoc/pickles/releases/tag/v1.1.0
