### ISSUE TITLE
[Wish] Align scenario keywords to the right side so that step texts start from the same position

### ISSUE THREAD

**Issue by sergeyshushlyapin** [picklesdoc/pickles#195]
Since the keywords `Given`, `When`, `Then` and `And`, `But` have different length, scenarios with numerous steps might be hard to read:
![image](https://cloud.githubusercontent.com/assets/4719165/7401826/c1ec034a-eecf-11e4-8e5b-39dc0a26ddcf.png)

Aligning them by the right side can make it more readable (IMHO):
![image](https://cloud.githubusercontent.com/assets/4719165/7401959/af461842-eed0-11e4-9a94-f7ac98b3136a.png)

Please let me know what do you think about this and whether I should send a PR. Thanks.

**Comment by dirkrombauts** [comment]
I fully agree with you and would be very glad to receive a pull request. Do you think you might be able to do this for the static HTML version as well?

**Comment by sergeyshushlyapin** [comment]
Hm.. That's yet another world... Would be nice to share the styles between these two, but that is definitely another request... I'll just update it independently for now.

**Comment by sergeyshushlyapin** [comment]
Before:
![image](https://cloud.githubusercontent.com/assets/4719165/7414567/4bafe380-ef5c-11e4-984f-1e53c5474854.png)

After:
![image](https://cloud.githubusercontent.com/assets/4719165/7414580/60369e0c-ef5c-11e4-83de-5888063dc6e2.png)

**Comment by sergeyshushlyapin** [comment]
Merged into master (https://github.com/picklesdoc/pickles/pull/196).

Thank you.

**Comment by dirkrombauts** [comment]
Released as part of version 1.1.0: https://github.com/picklesdoc/pickles/releases/tag/v1.1.0
