### ISSUE TITLE
Silent fail in case full filename is too long

### ISSUE THREAD

**Issue by cjaarts** [picklesdoc/pickles#199]
When the full file name of a feature file is too long, the parsing fails. An attempt is made to generate a warning. This triggers another exception as the FullName is too long.

File: DirectoryTreeCrawler.cs
Method: CollectFiles

See the statement in **bold** below

catch (Exception) {
            if (log.IsWarnEnabled) {
              log.Warn("The file {0} will be ignored because it could not be read in properly", **file.FullName** );
            }
          }

By reporting the directoryFullName and the file.Name separately, no new exception will be triggered and (some) output is generated for the other feature files.

**Comment by dirkrombauts** [comment]
Thank you for reporting this issue.

The bad news is that I have practically no time to do development on Pickles myself right now, but the good news is that I can review and merge pull requests :-)
