### ISSUE TITLE
Alignment of the word 'Given' in non-english

### ISSUE THREAD

**Issue by JoostVoskuil** [picklesdoc/pickles#209]
We are using Specflow in the Dutch language where Given is translated into 'Gegeven'.
See screenshot: Alignment of the word Gegeven is not properly aligned.

![naamloos](https://cloud.githubusercontent.com/assets/4078158/9008839/4ccd3310-379d-11e5-880a-d85f86dc9570.png)

**Comment by dirkrombauts** [comment]
Hi,

Dutch is my native language but I've never written a Feature file in Dutch :-)  I suspect other verbose languages suffer from this problem as well.

Again, how good are your web design skills? If you send me pull request, I'll publish an update early next week. If you are not well-versed in web design then I'll try to do it later next week.

**Comment by JoostVoskuil** [comment]
Hi Dirk,

Sorry for my late reply. Wil look into this this weekend!

Regards,

Joost

**Comment by JoostVoskuil** [comment]
Having problems with creating pull requests
Can be solved by:
\src\Pickles\Pickles\Resources\Html\css\structure.css

remove: width: 44px; from 'keyword css entry'

**Comment by dirkrombauts** [comment]
There were some other lines to be deleted as well :-)
