### ISSUE TITLE
Add support for SpecRun test results

### ISSUE THREAD

**Issue by dirkrombauts** [picklesdoc/pickles#21]
I'm trying to find out whether [SpecRun](http://www.specrun.net/) can output some easily parsable results.

**Comment by elikhodadadi** [comment]
Hi, 

I tried to use the specrun results for Pickles, but i couldn't. also i read this articlehttp://docs.picklesdoc.com/en/v1.0/IntegratingTestResultsFromSpecRun/  to generate a reasonable result for pickles. i change the template file but it didn't help me.

Thanks in advance.
some parts of myproject.proj and .srprofile files are in the following:
myproject.proj file:
<PropertyGroup>
    <FeatureDirectory>.\myproje\features</FeatureDirectory>
    <OutputDirectory>\myproje\output</OutputDirectory>
    <SystemUnderTestName>test</SystemUnderTestName>
    <SystemUnderTestVersion>v1.0</SystemUnderTestVersion>
   <ResultsFormat>specrun</ResultsFormat> 
 <ResultsFile>.\TestReports\testresult.html</ResultsFile>
    <DocumentationFormat>dhtml</DocumentationFormat>
</PropertyGroup>

This is my .srprofile file:
<TestProfile xmlns="http://www.specrun.com/schemas/2011/09/TestProfile">
  <Settings projectName="myproje" projectId="{...}" 
reportTemplate="My_ReportTemplate.cshtml"/>
  <Execution stopAfterFailures="2" testThreadCount="9" testSchedulingMode="Sequential" retryCount="10" retryFor="Failing" />

**Comment by dirkrombauts** [comment]
Could you provide me some more data, like the versions of pickles and specrun you are using, the customized report file, the output file of specrun, and one ore two anonymized feature files? Thanks.

**Comment by elikhodadadi** [comment]
<package id="Pickles" version="2.8.2" targetFramework="net45" />
 <package id="Pickles.MSBuild" version="2.8.2" targetFramework="net45" />
<package id="SpecFlow" version="2.0.0" targetFramework="net45" />
  <package id="SpecRun.Runner" version="1.5.2" targetFramework="net45" />
  <package id="SpecRun.SpecFlow" version="1.3.0" targetFramework="net45" />

**Comment by dirkrombauts** [comment]
@elikhodadadi you can zip the files, or rename them as .txt

**Comment by elikhodadadi** [comment]
Hi, 

did you see my files? what do you think? what is the problem?

**Comment by dirkrombauts** [comment]
Unfortunately I did not see your files. All I am seeing is a post with empty lines followed by "the output of specrun is a html file". That is why I advised you to rename or zip your files.

**Comment by elikhodadadi** [comment]
[list.txt](https://github.com/picklesdoc/pickles/files/454903/list.txt)
[My_ReportTemplate.txt](https://github.com/picklesdoc/pickles/files/454904/My_ReportTemplate.txt)
sorry, I prefer to not attach the report of my tests. The output of specrun is a html file.
thanks.

**Comment by dirkrombauts** [comment]
Hi,
I will try out your report template, probably tomorrow.
I respect your decision not to share the report of your tests. As a result, my ability to help you will be severely limited. If I do not have the report file, then I cannot use it to debug Pickles.

Perhaps you can share the following: near the end of the specrun html file (near the `</body>` element) the Pickles-related output should appear - between `<!-- Pickles Begin` and `Pickles End -->`. That is the relevant part of the specrun html file.

Another option: if you are willing to share (some of) the specrun html file but do not want to share it publicly, you can email the files to dirk dot rombauts at picklesdoc dot com. I will treat anything you send me as confidential.

**Comment by dirkrombauts** [comment]
I'm sorry, I won't be able to look into this this week. I will do my best to investigate it next week.

**Comment by dirkrombauts** [comment]
I looked at your list feature file, and I think it is in an invalid format. Could you please try to generate your living documentation using pickles _without testresults_ and see if it is generated correctly?

The line `	Examples: Valid` is not valid gherkin. If you want to add some kind of comment to the examples section, you should use tags or comments like this:

```
@valid
Examples:
```

```
# valid
Examples:
```

**Comment by dirkrombauts** [comment]
Forget about my last comment (I deleted it). I was mistaken.

**Comment by dirkrombauts** [comment]
I'm afraid I won't be able to help you without a copy of your test result file. I'm sorry.
