### ISSUE TITLE
Max out tables

### ISSUE THREAD

**Issue by JoostVoskuil** [picklesdoc/pickles#210]
Is it possible to maxout the table with variable width?
See screenshot where 'Maximum salaris arbeidsverhouding' is printed into two rows.

![naamloos](https://cloud.githubusercontent.com/assets/4078158/9008844/5aed682a-379d-11e5-860c-394b7648a3dc.png)

**Comment by dirkrombauts** [comment]
Hallo Joost,

Thanks for your input. Getting the tables right is a really hard problem - I've had other people complain that they were too wide.

How good are your web design skills? I would welcome a pull request that makes the tables look good both in case they have a lot of data and have little data.

**Comment by JoostVoskuil** [comment]
Cannot reproduce anymore with latest version
