### ISSUE TITLE
If test results from MSTest also contains ordinary unit tests results (including to SpecFlow) then pickles fails with NRE

### ISSUE THREAD

**Issue by eugene-sea** [picklesdoc/pickles#212]
In my project I have SpecFlow tests and ordinary unit tests. Thus MSTest test results contains results of both. Unfortunately pickles currently does not handle this scenario.

Ordinary unit tests may not have "Description" element, so MsTestSingleResults.NameOf() fails with NRE for non-SpecFlow unit-tests.

Stack trace of the issue:
<img width="734" alt="screen shot 2015-08-11 at 11 44 45 am" src="https://cloud.githubusercontent.com/assets/8311344/9193751/6f51a752-401e-11e5-8cd5-b38d8db06f0f.png">

This may be fixed like this:

    private IEnumerable<XElement> AllScenariosInResultFile()
    { 
        return this.resultsDocument.Root.Descendants(ns + "UnitTest").Where(s => s.Element(ns + "Description") != null);
    }

I have added "Where(...)" to filter out test results without "Description" element. This works fine in my case.

**Comment by dirkrombauts** [comment]
Thanks for the heads up! Could you perhaps send me a pull request?

**Comment by eugene-sea** [comment]
Yes, I will do in few days
