### ISSUE TITLE
Add support for keywords such as "Background"

### ISSUE THREAD

**Issue by mikeblakeuk** [picklesdoc/pickles#215]
Background: using Visual Studio and SpecFlow

Given: I have a .feature file
When: I have the term "background" in the feature
Then: pickles should gerenate html for that feature

**Comment by dirkrombauts** [comment]
I'm afraid I don't understand what you mean. Pickles does support the "Background" keyword. Are you saying that you found a bug in Pickles?

How exactly are you using Pickles?

**Comment by mikeblakeuk** [comment]
Using SpecFlow in VS
```
Feature: Schema
	In order to xxx...

Background: A Folder yyy...

@TagZZZ
Scenario: Defining a aaa...
```
Using the Command Line exe (via NuGet)

2015-09-23 11:33:25.1801|WARN|DirectoryTreeCrawler|The file Schema.feature in directory C:\git\xxx.Tests.Web\Features\Schemas will be ignored because it could not be read in properly

If i comment out background it works

**Comment by dirkrombauts** [comment]
Just for my understanding: are you running Pickles in a command line window, or in the visual studio Package Manager console?

**Comment by mikeblakeuk** [comment]
`"..\packages\Pickles.CommandLine.1.2.1\tools\pickles.exe" --feature-directory=Features --output-directory=App_Data\Scenarios --test-results-format=nunit --link-results-file=App_Data\TestResult.xml --documentation-format=Dhtml`

Command line for now (i want to run it on TeamCity in the long term).

(Also, i assume this is ready for Nunit 3.0 yet)

**Comment by dirkrombauts** [comment]
We don't actively support NUnit 3 yet. We're not actively blocking it either so your mileage may vary. You could try - for the sake of experiment, not as a solution to your problem - to leave out the test results and see if the html is then rendered.

**Comment by dirkrombauts** [comment]
Hi,
After studying NUnit 3, I noticed that NUnit 3 has a new test result format. I therefore highly doubt that NUnit3 will work with Pickles. Could you please try to reproduce the problem without including a test result file?

Is there any special reason why you are using NUnit 3?

**Comment by dirkrombauts** [comment]
I was able to diagnose the problem with the `Background` keyboard, though. The problem derives from the way you use the `Background` in your scenario.

It looks to me as if you are using the `Background` keyword to provide additional, "background" information about the feature. It's a common mistake, but that is not what the `Background` keyword is for. 

The background keyword is used to specify steps (Given, When and/or Then) that are executed *before* each scenario.  Have a look at https://github.com/cucumber/cucumber/wiki/Background for more information on the `Background` keyword.

**Comment by dirkrombauts** [comment]
Is your question answered? Can I close the issue?

**Comment by mikeblakeuk** [comment]
I think so. Thanks for the help.
