### ISSUE TITLE
The PowerShell cmd should trace relative paths from the current directory

### ISSUE THREAD

**Issue by mikeblakeuk** [picklesdoc/pickles#216]
Paths with dots in quotes should move up directories
For example if `c:\git\web-wrongFolder\` exists
```
C:\git\src\Company.Product\Company.Product.Tests.Web> 
Pickle-Features -FeatureDirectory .\Features -OutputDirectory Html -TestResultsFormat nunit -TestResultsFile "TestResult.xml"
Pickles v.1.2.1.0

Generating documentation based on the following parameters
----------------------------------------------------------
Feature Directory         : c:\git\web-wrongFolder\
Output Directory          : C:\git\web-wrongFolder\Html
Project Name              :
Project Version           :
Language                  :
Incorporate Test Results? : Yes
Test Result Format        : NUnit
Test Result File          : C:\git\web-wrongFolder\TestResult.xml
```

**Comment by dirkrombauts** [comment]
If I understand your example, you expect `Feature Directory` to be `C:\git\src\Company.Product\Company.Product.Tests.Web\Features` and `Output Directory` to be `C:\git\src\Company.Product\Company.Product.Tests.Web\Html`.

Is that what you have in mind?

**Comment by dirkrombauts** [comment]
It seems there is indeed a problem with the PowerShell commandlet: it appears to be unable to deal with relative paths, or rather it traces relative paths from the `USERPROFILE` rather than from the current directory.

**Comment by dirkrombauts** [comment]
I'm adapting the title to reflect the new insight.

**Comment by mikeblakeuk** [comment]
Thank you for you support and fast responses.

**Comment by dirkrombauts** [comment]
You're welcome. I will release a bug fix for this issue later today.
