### ISSUE TITLE
Pickles DHTML performance benchmarking

### ISSUE THREAD

**Issue by faisalhussain** [picklesdoc/pickles#221]
![image](https://cloud.githubusercontent.com/assets/5527438/10511778/94f4af84-7333-11e5-8dc1-58d4a17db3b9.png)

Hi, Looking at the structure of generated DHTML report. Everything is contained in pickles.js and therefore if we have massive number of feature files. Performance is issue, because browser takes time to load this pickles.js. 

We did some benchmarking. Results attached.

Why will we have ~5000 feature files. We are implement pickles cross project. One pickles website for all projects. We will have one input folder where everyone will drop features. Pickles.exe will read this folder and generate dhtml report. It will allow searching for tags across project and things will be more transparent.

Any suggestions we should try differently to get improved performance ?

**Comment by dirkrombauts** [comment]
Wow ... 5000 feature files. I'm speechless. There's little you can do with Pickles itself to improve the performance :-(

- What browser do you use? Try using a browser with fast JavaScript speed, like Google Chrome
- The static HTML version does not support search, but will load much faster
- If you are OK with having your documentation in the cloud (and potentially pay for having them private), you could have a look at relishapp.com

Beyond that: which problem are you trying to solve with "searching for tags across projects"?1

**Comment by dirkrombauts** [comment]
I'm closing this issue because the original poster has not provided new information for a long time.
