### ISSUE TITLE
MSBuild configuration should map Language too

### ISSUE THREAD

**Issue by Duranom** [picklesdoc/pickles#236]
Unlike powershell and commandline it is not possible to set the Language for the MSBuild runner.
Setting Pickels_Language is not mapped.

**Comment by dirkrombauts** [comment]
Thanks for the catch!

Would it be at all possible for you to contribute a fix?

**Comment by dirkrombauts** [comment]
I'm starting on this now.

**Comment by dirkrombauts** [comment]
@Duranom could you please double-check? The property is called `Language`. Did you read `Pickles_Language` in our documentation? If so, could you point me to the page so I can correct it? Thanks!

**Comment by dirkrombauts** [comment]
@Duranom I think I understand your request now - I got it backwards.

My current understanding is that you expect to be able to set a property `Pickles_Language` for the MSBuild runner, and that this property sets the language of the feature files.

Could you please confirm that I understood you correctly?

As I wrote earlier, you can set the language using the `Language` property, but I am the first to admit that that is not consistent with the other properties (as seen at http://docs.picklesdoc.com/en/latest/MSBuildTask/).

If I understood you correctly now, I am willing to add the `Pickles_Language` property for the sake of consistency.

**Comment by dirkrombauts** [comment]
Released with [v2.1.0](https://github.com/picklesdoc/pickles/releases/tag/v2.1.0).
