### ISSUE TITLE
The PowerShell runner does not load

### ISSUE THREAD

**Issue by dstj** [picklesdoc/pickles#239]
Hi,

The powershell module for Pickles crashes my Powershell process on Windows 10.

Just running the following command in a PS1 script and get the "Windows PowerShell has stopped working" popup. Regardless of the actual files in the `doc-temp` folder. Even empty or non-existent folder crashes.
```
Import-Module <path>\PicklesDoc.Pickles.PowerShell.dll
Pickle-Features -FeatureDirectory "c:\temp\doc-temp" -OutputDirectory "c:\temp\doc"
```

When clicking `Debug`, this is the exception visible in Visual Studio:
```
Unhandled exception at 0x00007FFB452C492E (ntdll.dll) in powershell.exe: 0xC0000005: Access violation writing location 0x0000000837700FD0.
```

My PowerShell version table is:
```
C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Any helps or ideas?  Thanks.

**Comment by dirkrombauts** [comment]
Hi,

I'm sorry you ran into troubles; thank you for taking the time to report them.

I just released a new version of Pickles with a bug fix - could you please try again with the new version? If the problem still exists I will do my best to fix it in the next couple of days.

**Comment by dstj** [comment]
Hi,

Thanks for the quick follow-up! Unfortunately, the problem is still there with version 2.0.3. The "Debug" message is a bit different (the dll name), but that may be unrelated, I do not know:

```
Unhandled exception at 0x00007FFB2A19A397 (clr.dll) in powershell.exe: 0xC0000005: Access violation writing location 0x000000474DD40F00.
```

**Comment by dstj** [comment]
Before the Powershell window crashes, I get the following output: `Process is terminated due to StackOverflowException.`

**Comment by dirkrombauts** [comment]
I have some news here: I was able to reproduce the problem. It seems to be a loading issue with the assemblies that are compiled into the pickles assembly as resources.

I will try and create a new version that does not compile external assemblies as resources.

**Comment by dirkrombauts** [comment]
Hi,

I released a new version. Could you try and verify whether this new version solves your problem? Thanks!

**Comment by dstj** [comment]
Hi Dirk,
It works now. Thanks for fixing it quickly! :+1:

**Comment by dirkrombauts** [comment]
You're welcome, glad I could help!
