### ISSUE TITLE
Word document is corrupt if a Feature has no description

### ISSUE THREAD

**Issue by xDazedx** [picklesdoc/pickles#261]
I am using the msbuild nuget package and when the features.docx is opened, I am receiving an error. I am using Word 2013.  

"We're sorry. We can't open features.docx because we found a problem with it's content."
clicking details displays:
"A document must contain exactly one root element. Location: Part: /word/document.xml, Line 1, Column: 0"

Is this a bug or is it something on my end? The html format looks fine!

![1-14-2016 1-31-40 pm](https://cloud.githubusercontent.com/assets/12139018/12336717/34ed0b36-bac3-11e5-90a5-1a3dc7d2f047.png)

**Comment by dirkrombauts** [comment]
I am sorry, I cannot reproduce this problem with my test data.

Which runner are you using? Are you including test results? Would it be possible to send me the project with the feature files so that I can try for myself?

**Comment by xDazedx** [comment]
Thanks Dirk. I am using SpecRun with Jenkins and not doing test results as of yet. I added a command line argument in the msbuild section of the Jenkins Project like the below. As mentioned, the HTML is building fine but when I change the output to word, I get the error opening the doc. Unfortunately I can't send you the project. 

I am going to add pickles to a few more projects and that should tell me if it is project specific or something else. Thanks for the help!

/p:Pickles_Generate=True /p:Pickles_FeatureDirectory=C:\ProjName\UI\Selenium_Automation\Tests /p:Pickles_DocumentationFormat=html /p:Pickles_OutputDirectory=C:\ProjName\UI\Selenium_Automation\TestResults\Pickles

**Comment by dirkrombauts** [comment]
Yes, please try it on a few more projects ... maybe you could try a sample project that you are allowed to send me and see if the problem occurs.

While we are on the topic of the Word output format: I'm curious why you use it. I personally have no use for it, so I'm interested to know what needs you address with it.

**Comment by xDazedx** [comment]
I work for a company that due to what we do, we are extremely locked down. When I run our automation through Jenkins, I attach the specrun report to an email and send it out after the run. My goal was to attach the word document along with the test results. The html version is available but that server is locked down so they have to have permissions to access it. The word attachment was just an easy way to send it out.

**Comment by dirkrombauts** [comment]
I have experience with locked down environments :-) Another alternative would be to zip the directory of the static html version. The static html version is meant for easy portability, so it can be zipped, ftp'ed, copied to a usb thumb drive, ...

**Comment by tboksebeld** [comment]
Hi,
Did you find the cause of this issue ?

I tried pickles for the first time today. Html was fine but I met the same error with Word. Unfortunately you do not have any error message with commande line but I tried the same operation with picklesui to generate Word documentation and I got a NullReferenceException in the output window.

There is maybe a dependency or something we forgot.
Did you find something about it ?
 
![untitled](https://cloud.githubusercontent.com/assets/10863987/13106598/75127fdc-d569-11e5-94aa-1b5e7bcb1b86.png)

**Comment by xDazedx** [comment]
I ended up just using a zipped version of the html since I could not resolve this. It happened on multiple projects.

**Comment by dirkrombauts** [comment]
I was unable to reproduce this problem on my system so far :-(

@tboksebeld are you able to share the project data that lead to this problem? I'll happily sign an NDA if needed.

**Comment by tboksebeld** [comment]
I solved my problem. 
I don't know which step of the environment setup i failed or forgot.
I uninstalled all and re-install depencies and pickles step by step and it now works fine.
It was maybe and issue due to my features file cause I reworked it too.

Anyway, find a NullReferenceException while executing picklesui product was surprizing ;-)

**Comment by dirkrombauts** [comment]
@tboksebeld do you know what you changed in the feature files?

@xDazedx did you try the UI version of Pickles? Did you get an error message there?

**Comment by dirkrombauts** [comment]
Good news. Thanks to the screenshot provided by @tboksebeld I was able to reproduce the problem. It will soon be fixed, and I will create a new release next week.

**Comment by dirkrombauts** [comment]
Released in version [2.4.0](https://github.com/picklesdoc/pickles/releases/tag/v2.4.0).

**Comment by xDazedx** [comment]
Thank you for fixing this issue!

**Comment by dirkrombauts** [comment]
My pleasure :-)
