### ISSUE TITLE
xUnit1 and xUnit2: Failure when tests are included that don't have traits.

### ISSUE THREAD

**Issue by iamkoch** [picklesdoc/pickles#268]
@line 93 of XUnit2SingleResults.cs

        private assembliesAssemblyCollection GetFeatureElement(Feature feature)
        {
            var query = from collection in this.resultsDocument.assembly.collection
                        from test in collection.test
                        from trait in test.traits
                        where trait.name == "FeatureTitle" && trait.value == feature.Name
                        select collection;

            return query.FirstOrDefault();
        }

There is an expectation that all tests returned will have a trait. If an assembly has a test that has no trai attribute the ```trait.name``` call fails. The real requirement is that all the tests must have a trait and one of those traits names must be "FeatureTitle".

For now I am running xUnit across a specific namespace in order to circumvent this issue.

**Comment by dirkrombauts** [comment]
I do not fully understand the problem ... are you saying you have tests without the FeatureTitle trait? Do you perhaps have both specflow-based tests and regular unit tests in the same project?

**Comment by iamkoch** [comment]
Hi there

Indeed I do. The fix would be simple and then this hybrid assembly would
supported by pickles
On Mon, 18 Jan 2016 at 19:49, Dirk Rombauts <notifications@github.com>
wrote:

> I do not fully understand the problem ... are you saying you have tests
> without the FeatureTitle trait? Do you perhaps have both specflow-based
> tests and regular unit tests in the same project?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/picklesdoc/pickles/issues/268#issuecomment-172633455>.
>
-- 
Antony Koch
e: ant@iamkoch.com
w: http://iamkoch.com
w: http://amko.info

**Comment by dirkrombauts** [comment]
I see. This is probably something I should verify with the other test result parsers as well.

Unfortunately I will not have time to look into this until thursday afternoon. So I am glad you found a workaround.

**Comment by dirkrombauts** [comment]
I'm not sure I understood you correct after all. I added a regular unit test to the test harness, resulting in this element in the test result xml:

```
    <collection total="1" passed="1" failed="0" skipped="0" name="Test collection for Pickles.TestHarness.xunit.RegularUnitTest" time="0.000">
      <test name="Pickles.TestHarness.xunit.RegularUnitTest.ThisTestPasses" type="Pickles.TestHarness.xunit.RegularUnitTest" method="ThisTestPasses" time="0.0001869" result="Pass" />
    </collection>
```

The test has no traits at all, not even an empty `<traits>` element. If I understood you correctly, this should cause a crash. The unit tests still pass, though.

Could you try to explain what I'm missing? Thanks!

**Comment by iamkoch** [comment]
Hi Dirk

That's interesting. Perhaps the missing piece is that these tests were
Xbehave tests. Leave it with me and I will see if I can reproduce and
provide you with more concrete evidence, if any, rather than you spending
any more time on it.
On Thu, 21 Jan 2016 at 12:17, Dirk Rombauts <notifications@github.com>
wrote:

> I'm not sure I understood you correct after all. I added a regular unit
> test to the test harness, resulting in this element in the test result xml:
>
>     <collection total="1" passed="1" failed="0" skipped="0" name="Test collection for Pickles.TestHarness.xunit.RegularUnitTest" time="0.000">
>       <test name="Pickles.TestHarness.xunit.RegularUnitTest.ThisTestPasses" type="Pickles.TestHarness.xunit.RegularUnitTest" method="ThisTestPasses" time="0.0001869" result="Pass" />
>     </collection>
>
> The test has no traits at all, not even an empty <traits> element. If I
> understood you correctly, this should cause a crash. The unit tests still
> pass, though.
>
> Could you try to explain what I'm missing? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/picklesdoc/pickles/issues/268#issuecomment-173554123>.
>
-- 
Antony Koch
e: ant@iamkoch.com
w: http://iamkoch.com
w: http://amko.info

**Comment by iamkoch** [comment]
Hiya

If I add one of the rows from my results XML into the top collection of results-example-xunit2.xml all the tests fail:

```xml
    <collection total="1" passed="1" failed="0" skipped="0" name="Test collection for Pickles.TestHarness.xunit2.MinimalFeatures.PassingFeature" time="0.003">
      <test name="Pickles.TestHarness.xunit2.MinimalFeatures.PassingFeature.PassingFeaturePassingScenario" type="Pickles.TestHarness.xunit2.MinimalFeatures.PassingFeature" method="PassingFeaturePassingScenario" time="0.00295" result="Pass">
        <traits>
          <trait name="FeatureTitle" value="Passing" />
          <trait name="Description" value="Passing Feature Passing Scenario" />
        </traits>
      </test>
      <test name="A.B.C.D(routeMessages: A.Type, accountService: Castle.Proxies.IAccountServiceProxy, balanceService: Castle.Proxies.IBalanceServiceProxy, mqDispatcher: Castle.Proxies.IQueueMessages`1Proxy_1, handler: A.Type, testServer: Microsoft.Owin.Testing.TestServer, myCommand: A.Module) [01] Given An online user doing something" type="A.SOmething" method="MyMethodName" time="0.1484707" result="Pass" />
    </collection>
```

**Comment by iamkoch** [comment]
Even adding your test collection mentioned above in makes all the tests in "WhenParsingxUnit2ResultsFile" fails

**Comment by iamkoch** [comment]
changing line 96 to 

```c#
from test in collection.test where test.traits != null
```

makes those particular tests pass where they failed before

**Comment by dirkrombauts** [comment]
Weird that it works on my machine - something must be wrong in my configuration.

**Comment by iamkoch** [comment]
Very strange. Just to be sure I've run the tests through the resharper test runner and NCrunch and both cause failures. http://iamkoch.com/wp-content/uploads/2016/01/Capture.png

**Comment by dirkrombauts** [comment]
Aha ... the position of the xml fragment makes a difference. If I put your fragment (with `<test name="A.B.C.D(..." />` then all xunit2 tests are red.

**Comment by iamkoch** [comment]
Heh, that's bizarre! Glad you've managed to reproduce it though. Was concerned I was doing something insane...

**Comment by dirkrombauts** [comment]
Really weird that the xml deserializer accept the version where my fragment is in the middle, but not where my fragment is the very first collection.

**Comment by dirkrombauts** [comment]
I now managed to create a properly reliable unit test that demonstrates the problem, and I fixed the problem as well. I'm going to check the other test result providers too, but you can expect a new version of Pickles in the next couple of days.

**Comment by dirkrombauts** [comment]
The heavy lifting is done. I still need to dot some i's and cross some t's in the changelog, but I expect to release a new version of Pickles tomorrow (Monday).

**Comment by dirkrombauts** [comment]
Released in [v2.2.1](https://github.com/picklesdoc/pickles/releases/tag/v2.2.1)

**Comment by iamkoch** [comment]
Great work @dirkrombauts

**Comment by dirkrombauts** [comment]
Thanks, glad I could help.
