### ISSUE TITLE
Output commented lines

### ISSUE THREAD

**Issue by CharlieMott** [picklesdoc/pickles#271]
It would be great if the commented (#) lines in a feature file were output. Maybe an optional parameter. I use Specflow + powershell to generate html output.

**Comment by dirkrombauts** [comment]
Thank you for your suggestion. This has been impossible to do in the past since the parser of the feature files swallowed the commented lines and Pickles never received them. We are now using a new version of the parser so it is time to re-investigate this.

**Comment by dirkrombauts** [comment]
Released in version [2.6.0](https://github.com/picklesdoc/pickles/releases/tag/v2.6.0)

**Comment by jamiesmy** [comment]
Is there a way to turn off Comment Output in 2.6?

**Comment by dirkrombauts** [comment]
hi, no, there's not. I'm assuming you want to turn it off, and i'm curious about why. What do you use the comments in `.feature` files for?

**Comment by jamiesmy** [comment]
We have one team that has been trained to use comments to convey some particular technical implementation detail to the developers that they do not want published to the stakeholders or the support team

**Comment by dirkrombauts** [comment]
I see ... The progress of Pickles depends greatly on contributions from the community, so if you send me a pull request that adds parameters to all the runners then I'll be happy to include that.

**Comment by CharlieMott** [comment]
Works great.  Many many thanks.
(one very minor niggle, I would have chosen green to match comment styles in Visual Studio).
