### ISSUE TITLE
Support Cucumber JSON Format as Output

### ISSUE THREAD

**Issue by dirkrombauts** [picklesdoc/pickles#278]
Cucumber specifies [JSON report format](http://cukes.info/reports.html) generated e.g. by Cucumber-JVM. It can be used as input for different visualization tools, e.g. for [Cucumber-JVM Reporting for Jenkins](https://github.com/masterthought/jenkins-cucumber-jvm-reports-plugin-java) which visualizes execution results for Jenkins Jobs.

Since Specflow itself seems not to support JSON as output format, but Pickles [does](http://www.picklesdoc.com/#!Pages/ArgumentsDocumentationFormat.md) I hoped to use Pickles to convert Specflow output to JSON and then use this as input for Jenkins reporting. But it seems that Pickles JSON format is different from format used by Cucumber.

It would be very useful if Pickles supported Cucumber JSON Format as output.

Sent by [Slawa Giterman](https://pickles.uservoice.com/admin/users/50985607-slawa-giterman) on UserVoice.

**Comment by dirkrombauts** [comment]
don’t fully understand the requirement, though. It reads as if you want to use Pickles as a converter between different JSON formats.

What should the resulting “Cucumber JSON” format look like? Could someone provide an example?

Any feedback/clarification would be appreciated!

**Comment by jgrossrieder** [comment]
Here is an example: https://www.relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter

**Comment by dirkrombauts** [comment]
Thanks for the information!

I can't give any estimates on when this will be done. The fastest way to make it happen is to create a pull request.

**Comment by jgrossrieder** [comment]
I'm sorry, I'm not familiar with the Git/GitHub process, I don't know what a Pull Request is

**Comment by dirkrombauts** [comment]
No problem ... there's a pretty good introduction to the GitHub process over there: https://guides.github.com/activities/hello-world/

**Comment by jgrossrieder** [comment]
Ok thank you. So It means that I've to fix it myself, but I don't know this product, I cannot make a fix for it

**Comment by dirkrombauts** [comment]
I understand that it's not easy to work with someone else's code. If you don't have the time, resources or inclination for it, then don't do it :-)

But the reality of the situation is that feature requests like these - where only one or two people want it - tend to sit around for a long time before someone implements it. Open source projects depend on input from other people.

**Comment by samholder** [comment]
You say 'I don't know this product, I cannot make a fix for it' which might be true, but in my experience you often don't need to know how everything works to implement a single focused thing. My advice would be to spend a little time having a look and trying to determine what needs to be done to implement what you want. you might find it's easier than you think :)

**Comment by samholder** [comment]
I think the existing [JSON documentation builder](https://github.com/picklesdoc/pickles/tree/6570b6c2bfc230467a297bc332b69c81d245e0f8/src/Pickles/Pickles/DocumentationBuilders/JSON) would be a good place to start as I imagine you can copy that and tweak it for cucumber JSON.

But I'm no expert and have never used Pickles or seen the code, thats just from a quick search and look.

**Comment by jgrossrieder** [comment]
Me neither, I'm currently trying to understand it, but I'm not sure it is the right tool, I need only my test results to be "exported", not the other features that are not concerned by my test run.

**Comment by jgrossrieder** [comment]
I started some implementation, but I'm blocked on severals points to generate a cucumber report:
Cucumber seems to have a result for each step of a scenario, pickles import only one result per scenario. Also, cucumber results mentions the lines, and I don't have them available on each step

**Comment by dirkrombauts** [comment]
Pickles does indeed support only scenario-level results at the moment, not step-level (unfortunately).

The reason is that most supported test runners supply only scenario-level results. If you are coming from SpecFlow, I am not aware of a test runner that offers step-level results. Please tell me if you know of one.

**Comment by jgrossrieder** [comment]
I just checked the XML from NUnit(3), it's not very readeable, but there is, within the Output the list of steps with "done" or "error", which would allow to know which step did fail

**Comment by dirkrombauts** [comment]
You are right, the information is in the output file. So I try to express myself more accurately: the xml structure of the test runner's output file supports only scenario-level results.

It would be possible to parse out the result of the individual steps by looking at the `CDATA` content of the `output` element (in NUnit3) - and I believe there's a feature request for that even though I can't find it at the moment - but it would take a considerable effort to do this properly for all supported test runners. This comes down - again - to involvement from the community I'm afraid.

**Comment by jgrossrieder** [comment]
I'm almost done with the implementation. 
It is working fine, I just have one information missing. There is the notion of "evidence" of failure or success with Cucumber, which is basically a message indicating the result.

Would it be possible at least to get the content of "Output" as a single string field? That would greatly help when checking the result. I can maybe do it for NUnit3, but for other framework, I'm not aware of the result.

**Comment by dirkrombauts** [comment]
Thank you for your time and effort! I'm on the road today and most of tomorrow, so I won't be able to give a full answer until Friday.

The short answer: exposing the Output as a string on the scenario makes sense, I think. You can populate it with the content of the output element of NUnit3. Other test framework should be similar.

**Comment by dirkrombauts** [comment]
@jgrossrieder do you need more information about the Output string aspect?

**Comment by sqavenky** [comment]
Has this feature added to Pickle? We are also looking for solution where SpecFlow can generate a json format that can be consumed by Cucumber reports and publish a html in Jenkins. Pickle is good for this scenario but we want a json output in cucumber json format for cucumber sandwich report to consume.
Any progress you guys make, please let us know. We are interested in the solution.

**Comment by jgrossrieder** [comment]
There is a Pull request I made #359 but due to no unit test, it has noot been added

**Comment by dirkrombauts** [comment]
It is my policy to have unit tests for all the code in Pickles. There is some older code that does not have unit tests, but for all new code I require unit tests.

@sqavenky the fastest way to have a feature added to an open source project is to do it yourself and send a pull request. Maybe you have times to build upon #359 by @jgrossrieder and add unit tests?

**Comment by grofit** [comment]
Sorry to resurrect this one, but I am looking at using Pickles as a way to get specflow to output some cucumber compatible json to then use one of the npm html generator things.

Anyway the issues seems to be when I generate the json file its fine, but its missing a `uri` section and when the generators go to use it, they blow up because they cannot find it. So is this something that needs fixing (on your side or theirs)?

**Comment by dirkrombauts** [comment]
Thanks for your interest in the cucumber json format.  I really mean that!

The truth is that I'm not happy with the current version of that output format. It doesn't seem to work properly with scenario outlines (see the discussion above), now you mention a missing `uri` section, ...

I don't understand the cucumber json format enough to do anything meaningful within my current time constraints. I would be very happy if you would be able to contribute towards making the cucumber json output format more usable/useful!

**Comment by grofit** [comment]
If I had the time I would love to do so, at the moment I was just spiking on one of the projects here but its time boxed, and unfortunately I have many OS repos I maintain so I wouldn't be able to assist much in this area, but if I do somehow get some time will check back in with you.

**Comment by phillandrade** [comment]
Hi! Isn't this closed? I just used the cucumber output format and it's working nicely.

**Comment by dirkrombauts** [comment]
@phillandrade does it work for you with scenario outlines? The comments from July 2017 mention a missing uri section too. Do you have any thoughts on that?

**Comment by phillandrade** [comment]
@dirkrombauts  oh sorry, I see now. I'm actually not familiar with the Cucumber JSON format. I just stumbled across this open issue and noticed that the option was already there in the command line tool and it was "working", so I thought the issue was outdated or something. Thanks for clarifying.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
