### ISSUE TITLE
Search by labels on Feature level

### ISSUE THREAD

**Issue by albertdabrowski** [picklesdoc/pickles#282]
Unable to filter features by label in generated DHTML, e.g.

```
@LabelA
Feature: Feature A
....
```
In that case filter doesn't return anything (feature A and its scenarios)
Strange, as on html generated part every label on Feature level is propagated to every scenario.
I'm asking this as we label mainly features (not scenarios). Also would be great if I could filter with more than one label at the same time

**Comment by dirkrombauts** [comment]
Hi,

Are you saying that if you search for `@LabelA` in the DHTML version, you do not get any results? We definitely support this feature, so there must be a problem somewhere.

Could you please go to [the sample DHTML output](http://www.picklesdoc.com/Output/DHtml/Index.html) and search for `@allAboutTags`? Do you get any results? If not, could you please try in a different browser?

**Comment by albertdabrowski** [comment]
Hi again,
I did further testing as Your output worked and it seems I have had the old version of Pickles. On the 2.3.0 version it works as expected. The only thing it doesn't support is to specify more than one label in the search. Do You think that would be feasible to do this on DHTML version?

**Comment by dirkrombauts** [comment]
Regarding searching for more than one label: in what situations would that help you? What are you trying to achieve?

**Comment by albertdabrowski** [comment]
Well, we are doing labeling for marking specific features to the appropriate products we develop. Some of them are common for all products some of them are specific. So then I would like to filter by common AND specific product to have all features. There are other use cases as well. I know that in this case we may overcome with tagging feature with every product instead of common.

**Comment by dirkrombauts** [comment]
I created a new issue to track the feature of searching for more than 1 label: #283 . Could you please enhance that issue?
