### ISSUE TITLE
Customize/Extend Output?

### ISSUE THREAD

**Issue by kbrowns** [picklesdoc/pickles#294]
We make heavy use of specflow and pickles today for testing our commercial API's that my company builds and sells.  We share our pickle reports with our customers and it works great.  One request we get repeatedly is to have various trace information linked to from the feature text in the pickles report.  In other words people want to see the underlying API call's input and output (serialized json) that's being made in the steps behind the scenes.  We're looking for some kind of runtime hook that would be used to supply this trace data and have it included with the standard pickle output.  There appears to be heavy use of Autofac within Pickles which makes me think this type of extensibilty might be supported in some form today.  Doing post processing is another option, but wanted to check with the dev team and see if there's a cleaner way to do this.  I'm also curious if hear if something like this is on your roadmap if not already supported.  If yes, I could look into submitting a PR.

Thanks for making such a great product - we get great use out of it.

**Comment by dirkrombauts** [comment]
Thanks for the props, I'm glad you're getting such good use out of Pickles :-)

As I wrote in #241, Pickles is primarily meant as a Living Documentation tool. But every so often I get requests from people who want more detailed information. Currently, there is nothing in Pickles to match your need (despite our using Autofac ;-) ), but I am opening up to the idea.

I think the feature with the most value for everyone would be to somehow parse the output of the test runner and match that to the individual steps. I would be happy to consider any PRs you may send my way.

One more thing: if you need primarily a test report and only secondly a living documentation, then you might want to look into [SpecFlow+ Runner (formerly known as SpecRun)](http://www.specflow.org/plus/runner/). That is a test runner built specifically for SpecFlow, and creates beautiful (IMO) reports with the steps of the scenario on the one hand and the trace information on the other hand.

**Comment by dirkrombauts** [comment]
I'm closing this issue because there hasn't been any activity for a long time.
