### ISSUE TITLE
Multiple Format Output?

### ISSUE THREAD

**Issue by xDazedx** [picklesdoc/pickles#301]
Is there a way to have the build output 2 formats ie. html and word?

**Comment by dirkrombauts** [comment]
Do you mean the MSBuild runner by "the build"?

Not now. It would be a cool feature if you (or someone else) could make a pull request :-)

**Comment by dirkrombauts** [comment]
I'm closing this issue since there hasn't been any activity for a long time. Feel free to re-open it if this is still important to you.
