### ISSUE TITLE
An Overview Dashboard for the DHTML Pickles Site with Summary Charts by Namespace and Tags

### ISSUE THREAD

**Issue by dirkrombauts** [picklesdoc/pickles#306]
Created to track further development and comments to #295

**Comment by aaronjrich** [comment]
Hey @dirkrombauts, forgive my ignorance, can you help me understand where this experimental code is going?  Is it in the develop branch?  If you want to contribute, do you pull down a particular branch and commit to that?  Thanks!

**Comment by dirkrombauts** [comment]
@aaronjrich no problem. The code is in the develop branch like "real" code, but is only active if you provide the [argument for including experimental features](http://docs.picklesdoc.com/en/latest/ArgumentsIncludeExperimentalFeatures/).

**Comment by dirkrombauts** [comment]
@aaronjrich so if you want to contribute, just work like you did in the past with regard to branches

**Comment by huguesf** [comment]
The overview dashboard is a great feature. Is there a way to automatically open the doc on that dashboard? It provide a great overview and we can see at a glance if there is any test failure.
Thanks for the great work!

**Comment by dirkrombauts** [comment]
Hi,
Thank you for your kind words. There is no officially supported way of opening the page on the overview dashboard. You can of course modify the generated code to open the dashboard in a "document ready" handler, but you'd have to reapply that each time you regenerate the living documentation

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
