### ISSUE TITLE
Render standalone text or markdown file in DHTML output

### ISSUE THREAD

**Issue by azam-a** [picklesdoc/pickles#309]
I am switching from HTML format on an ancient version of Pickles (0.18.2), to the latest one (2.5.0), outputting to DHTML format.

I noticed that my standalone text file is no longer being generated. I have also tried converting the text file to markdown but it is also not working.

Is this the expected behaviour for DHTML output?

Thanks in advance

**Comment by dirkrombauts** [comment]
Hi, unfortunately the different output versions of Pickles don't always support the same features. This is one of them.

The static HTML version does still support additional files - I just verified this with version 2.5.0.

**Comment by azam-a** [comment]
Thanks for the clarifications Dirk.

You may close this issue :)

**Comment by dirkrombauts** [comment]
I'm closing it :-)
