### ISSUE TITLE
Hyperlink Feature #1: Automatic Hyperlink Generation for Scenario Titles

### ISSUE THREAD

**Issue by ajhuntsman** [picklesdoc/pickles#320]
Per @dirkrombauts (https://github.com/picklesdoc/pickles/issues/317#issuecomment-207935589), each Scenario's title should be rendered as a hyperlink to that Scenario.

By default, the hyperlink will be generated using the Scenario's title.

**Comment by dirkrombauts** [comment]
Thanks for creating the issue. It would actually be sufficient to include the `id` attribute to the heading of the scenario title.

Assuming we have a scenario like

```feature
Scenario: I'm Blue
```

Then for the static html version, we should generate

```html
<h2 id="im-blue">I'm Blue</h2>
```

The dynamic html version can be done in a similar way.

**Comment by eleite77** [comment]
Hi @dirkrombauts 
I am trying to implement that even i don't know well the project itself.

Do you think for this enhancement it is possible to detect a scenario parameter in the url (like scenario=title) and to filter the data in the JsonPWrapper javascript function?
The data.features array will only contain one entry : the filtered feature.

Then a javascript function can open the left tree navigation and filter in the right side the good scenario.

What do you think?
Could it be an easy way to implement that?
Thanks
E. Leite

**Comment by dirkrombauts** [comment]
@eleite77 thank you for the suggestion. To be perfectly honest, I don't know my way around the DHTML version all that much, so I cannot answer your question whether it would be easy to implement this.

**Comment by aaronjrich** [comment]
@dirkrombauts and @eleite77: I took a look at this at bit ago to assess the effort in the "DHTML" version doing something like a query string to link directly to a scenario.  In the current implementation, "#folder/featurefile.feature" was used on the URL to deep link to particular features. The nice part of using that was that it was easy to get at that last part of the url, you just call window.location.hash, and bam, you have the feature file name to filter for. In hindsight, given this new request, it would have been better to use a query string like structure to allow for more flexibility, but query strings are not nearly as easy to use on the client side.  I think it could be converted to that without too much effort but I worry a bit that, 1, some people may be expecting the hash url structure and 2, I'm not sure what to use for the anchor name and still have it be discoverable.  I tried using the scenario title, but then struggled a bit when weird characters were in the title (perhaps this was causing an issue: http://stackoverflow.com/questions/70579/what-are-valid-values-for-the-id-attribute-in-html/31773673#31773673).  Based on the Dirk's example above, all weird characters could get stripped away - perhaps that would help things.

I may take another stab at this when I have some time unless someone else would like to jump on this before me.

**Comment by ocsurfnut** [comment]
@dirkrombauts , @aaronjrich , @eleite77 , @ajhuntsman ... this is a feature I am interested in as well, and I actually find myself with a little free time this week.  Is anyone already working on this?  If not, would it be okay if I take this ball and run with it (based on suggestions above)?

**Comment by aaronjrich** [comment]
@ocsurfnut, go for it, I haven't been able to get after this.

**Comment by dirkrombauts** [comment]
@ocsurfnut I'm not working on it either, so go for it!

**Comment by dirkrombauts** [comment]
Released in version [2.8.0](https://github.com/picklesdoc/pickles/releases/tag/v2.8.0).
