### ISSUE TITLE
Investigate whether #315 applies to other unit test frameworks as well

### ISSUE THREAD

**Issue by dirkrombauts** [picklesdoc/pickles#326]

**Comment by dirkrombauts** [comment]
https://github.com/picklesdoc/pickles/pull/315

**Comment by dirkrombauts** [comment]
@danielpullwitt do you think you would have time to take a look at this one? Thanks!

**Comment by danielpullwitt** [comment]
How urgent is this? I can have a look at this but not immediately during the next few days as i'm very busy and this requires at least to run tests with all the affected frameworks.

**Comment by dirkrombauts** [comment]
Since I'd prefer to have parity on all unit test frameworks I'd prefer this sooner than later. There is actually an infrastructure in place to help with this, it's described in the [CONTRIBUTING.md](https://github.com/picklesdoc/pickles/blob/develop/CONTRIBUTING.md) file. Please let me know if the information there is enough to get you started. If you need more information, I'll happily provide it.

**Comment by danielpullwitt** [comment]
I probably have time to look at this tomorrow evening to find out how much effort is involved.

**Comment by danielpullwitt** [comment]
So far I´ve got the test results extended and tests set up and running. In three cases the test is failing (as expected); as soon as I find time I will fix the test providers.

**Comment by dirkrombauts** [comment]
Excellent, thanks!

**Comment by danielpullwitt** [comment]
While I could fix the test providers (nunit / xunit / vstest) for scenarios and scenario outlines, I now have problems with cucumber / cucumberjs:
createtestresults.cmd in the test result repository references programs not provided (I did not notice on my first try). Additionally I can not identify which versions are used and where to get them.

Could you provide the missing information?

**Comment by dirkrombauts** [comment]
Thanks for the heads-up, I'll do my best to provide the information by Monday evening (European time).

**Comment by dirkrombauts** [comment]
I added the information to the [README.md](https://github.com/picklesdoc/pickles-testresults/blob/master/README.md) for the pickles-testresults repository. Please let me know if you think I left something out.

**Comment by danielpullwitt** [comment]
In principle the setup works, but I got a problem with the javascript tests (there are "TypeError: callback.pending is not a function" messages). As I'm not deep into javascript development, I opted for manually editing the resulting json file and got everything else working. This is a little bit unsatisfactory but I have no clear idea about the nature of the actual problem.

**Comment by dirkrombauts** [comment]
I'm not a javascript expert myself, but if you push your code to GitHub I will take a look at it and try to help you.

**Comment by danielpullwitt** [comment]
They occur in the existing code, I also get a slightly different json output (more 'match' information), I don't know if its due to a different cucumber version or any other version / system dependent behavior

**Comment by danielpullwitt** [comment]
I just found on the cucumber-js page that for not implemented tests you now use
**callback(null, 'pending');**
instead of
**callback.pending();**
Shall I fix this in the test result repository?

**Comment by dirkrombauts** [comment]
Yes, please fix that - that's very kind of you!

**Comment by danielpullwitt** [comment]
Done, pull requests for test data and main pickles repository are available

**Comment by dirkrombauts** [comment]
Thank you again!

**Comment by dirkrombauts** [comment]
Released in version [2.6.1](https://github.com/picklesdoc/pickles/releases/tag/v2.6.1).
