### ISSUE TITLE
Sorting features in output file (MS Word)

### ISSUE THREAD

**Issue by JohnyDeath** [picklesdoc/pickles#357]
I'm trying to sort my features in output word file by the name of feature-files.

I have 2 files:

[01 - First step part one.feature.txt](https://github.com/picklesdoc/pickles/files/369213/01.-.First.step.part.one.feature.txt)
[02 - First step part two.feature.txt](https://github.com/picklesdoc/pickles/files/369214/02.-.First.step.part.two.feature.txt)

And when I convert it into "docx", i see:
![contents](https://cloud.githubusercontent.com/assets/5936030/16917453/5a48ee66-4d0a-11e6-8cd0-ecfc82297a6e.png)

I expected to see the feature "First step part one" in the beginning of the list-content

But when I rename a head of the first file to 
```
Feature: First Z-step part one
```
then I see correct word-file:
![contents-right](https://cloud.githubusercontent.com/assets/5936030/16917808/d70eee40-4d0b-11e6-8122-6a97b99d3651.png)

**Comment by dirkrombauts** [comment]
Thanks for reporting this issue!

**Comment by dirkrombauts** [comment]
@allustin not yet ... real life is interfering with my ability to do much coding. I will be happy to review any pull requests you may send my way though, and I usually do find the time to release new versions with contributions from other people.

**Comment by dirkrombauts** [comment]
Resolved by #373

**Comment by dirkrombauts** [comment]
Released in version [2.8.3](https://github.com/picklesdoc/pickles/releases/tag/v2.8.3).
