### ISSUE TITLE
Hyperlink markdown doesn't work in Feature: section

### ISSUE THREAD

**Issue by SubjectiveReality** [picklesdoc/pickles#367]
Hi- I'm trying to introduce SpecFlow and Pickles to my team, and one piece of feedback that came in was links to relevant Jira issues (or whatever) in places they may be needed in the feature files.  I have tried the markdown after both Feature: and Scenario: keywords, and it works great after the latter but not after the former.  Is this intentional for some reason?  Seems like having the option to link from the Feature: area would be nice as well as the Scenario: area.

Btw, I'm generating via command line with the following: -trfmt=specrun -df=dhtml

Works (creates link in dhtml output):
```
Scenario: blah blah
[my link](https://my.link.com/blah)
```

Doesn't work (outputs unmodified text):
```
Feature: blah blah
[my link](https://my.link.com/blah)
```

**Comment by dirkrombauts** [comment]
Thanks for taking the time to report this. This behaviour is certainly not intentional. I will do my best to investigate it this week, but it might take me until next week - my real life schedule is quite full at the moment.

**Comment by SubjectiveReality** [comment]
No worries- it's a fantastic tool and your time and effort is much appreciated!  I understand the busy schedule and am not worried about turn around time or anything like that.  Glad the feedback was helpful and might try to track it down myself, schedule permitting.  

Cheers

**Comment by dirkrombauts** [comment]
Thank you for your kind words.

**Comment by dirkrombauts** [comment]
I had a look at this ... the feature seems to work as expected, but could you please verify the following: Does the description part (that contains the link) start right next to the left margin?

I.e.

```
Scenario: blah blah
[my link](https://my.link.com/blah)
```
instead of
```
Scenario: blah blah
 [my link](https://my.link.com/blah)
```

The second version will cause Pickles to interpret the description as code instead of normal text.

**Comment by SubjectiveReality** [comment]
Wow, that was it, works fine without any indentation.  Sorry about that, I completely missed the difference in how I had it in my working case and non-working case.

**Comment by dirkrombauts** [comment]
No problem ... it's a known issue, and shouldn't be too difficult to fix if you feel up to it: https://github.com/picklesdoc/pickles/issues/302

**Comment by dirkrombauts** [comment]
Can this issue be closed?

**Comment by SubjectiveReality** [comment]
Yes, I think so.  I'll take a look at that issue and see if I can help.
