### ISSUE TITLE
DHTML version sorts features and folders in descending order

### ISSUE THREAD

**Issue by dirkrombauts** [picklesdoc/pickles#383]

**Comment by dirkrombauts** [comment]
Hmm ... on the local webserver: in Firefox the order is ascending, but in Chrome the order is descending. On a remote webserver, the order is descending in both Firefox and Chrome.

**Comment by dirkrombauts** [comment]
@aaronjrich do you have any idea what may cause this?

**Comment by Sjaaky** [comment]
Before f131a382b01359bcdb0ba720106d66762954946b the pickledFeatures.js contained the features in reverse order. Now the pickledFeatures.js is in alfabetical order. When the dhtml page loaded, the features are still reversed in [index.html jsonPWrapper](https://github.com/picklesdoc/pickles/blob/develop/src/Pickles/Pickles.BaseDhtmlFiles/Index.html#L487).

**Comment by dirkrombauts** [comment]
Released in version [2.11.0](https://github.com/picklesdoc/pickles/releases/tag/v2.11.0).
