### ISSUE TITLE
Test result file is read as null in CucumberJson when elements is missing

### ISSUE THREAD

**Issue by santus444** [picklesdoc/pickles#390]
[2016-11-15_21-28-10-499.txt](https://github.com/picklesdoc/pickles/files/593438/2016-11-15_21-28-10-499.txt)

Hi, When I execute the pickles on cucmberjson result files, pickles reads the path as null. 

```
C:\LoadT\Jenkins\workspace\execute_tests_and_generate_documentation_workflow_bas
e>C:\temp\Pickles-exe-2.10.0\Pickles --feature-directory=.\features --output-dir
ectory=.\living_documentation\dhtml --test-results-format=cucumberjson --link-re
sults-file=.\results\2016-11-15_21-28-10-499.json --documentation-format=dhtml
Pickles v.2.10.0.0

Generating documentation based on the following parameters
----------------------------------------------------------
Feature Directory              : C:\LoadT\Jenkins\workspace\execute_tests_and_ge
nerate_documentation_workflow_base\features
Output Directory               : C:\LoadT\Jenkins\workspace\execute_tests_and_ge
nerate_documentation_workflow_base\living_documentation\dhtml
Project Name                   :
Project Version                :
Language                       : en
Incorporate Test Results?      : Yes
Include Experimental Features? : No
Test Result Format        : CucumberJson
Test Result File          : C:\LoadT\Jenkins\workspace\execute_tests_and_generat
e_documentation_workflow_base\results\2016-11-15_21-28-10-499.json
Pickles did not complete successfully Value cannot be null.
Parameter name: source
```

I even tried passing in multiple file paths separated by semicolon. Attached result file as txt. Please rename it to .json

**Comment by dirkrombauts** [comment]
Thank you for taking the time to report this problem.

Does the problem happen only when you specify a path to the test results? Does it happen when you do not specify a path to the test results?

**Comment by santus444** [comment]
When you specify a file that doesn't exist, it just logs that it skips it as it could not find it. It throws this log on UI and moves on to doc generation. 

Found the root cause. 
Pickles fails to generate the doc when the result json file does not have "elements":[] array for any one of the feature file results in it. 
Example: For the below result json file, if there is no elements key, it fails. It passes even when the elements array is empty like below or the complete result json is empty []. But now when the element itself is missing. 
```
[
  {
    "line": 1,
    "name": "Canada Federal Income Tax",
    "description": "Calculate taxes for tax types",
    "id": "canada-federal-income-tax",
    "keyword": "Feature",
    "uri": "features/statutory/CanadaFederalIncomeTax.feature",
“elements”: []
  }
]

```
In our case, result files miss "elements" key when the Feature file with only one scenario is defined and it has a '@wip' tag (which we skip during cucumber execution with tag: ~@wip). This lead to not having any **elements** key in result file. 

Can pickles ignore this if its not present and generate the doc? Also, as this exception is thrown later, jerkins is not capturing it. The only thing I see on jenkins after running the pickles and if it encounters the above exception is 
```
C:\LOCATION_OF_EXECUTION>exit 1 
Build step 'Execute Windows batch command' marked build as failure
Archiving artifacts
```
We can only see the above exception for "null" if we run it from command line on the execution machine. 
Thanks.

**Comment by dirkrombauts** [comment]
Thank you for your further analysis. We had a similar issue with the MSTest provider not long ago, so this shouldn't be too difficult to fix. I hope to be able to release a fix sometime next week.

**Comment by santus444** [comment]
Thanks @dirkrombauts

**Comment by dirkrombauts** [comment]
Hi, real life interfered last week but I'm starting on this now.

**Comment by dirkrombauts** [comment]
Released in version [2.11.0](https://github.com/picklesdoc/pickles/releases/tag/v2.11.0).

**Comment by boris779** [comment]
Hi!

It seems there is a problem in Version 2.18.0
I have a cucumber-result.json with one feature where no scenario run (because this one runs only nightly) then I get the error message "... Value cannot be null, Parameter name: source"

After editing the json manually, it worked.

**Comment by dirkrombauts** [comment]
Hi,

Thanks for mentioning this. Could you please create a working sample (feature file and json file) that shows the error? That would greatly help me with fixing the error.

**Comment by dirkrombauts** [comment]
@boris779 any updates from your side? If not, I will close this issue.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
