### ISSUE TITLE
All scenarios are 'inconclusive'

### ISSUE THREAD

**Issue by pisten** [picklesdoc/pickles#391]
Using pickles console application.

First i run my tests using nunit3 with this command:
 `.\packages\NUnit.ConsoleRunner.3.5.0\tools\nunit3-console.exe .\CATS_Site\bin\Debug\CATS_Site.dll --where "cat == nightly" --result=./TestRapport.xml`

and get TestRapport.xml (re-saved as txt to be able to attach it).
Then I run pickles with the following command:
`.\packages\Pickles.CommandLine.2.10.0\tools\Pickles.exe --feature-directory=.\CATS_Site\Features --output-directory=.\Reports --test-results-format=nunit --link-results-file=.\TestRapport.xml --documentation-format=json`

The result will display that all my feauters are inconclusive, but in the test report we can see that the only test i ran did pass. I get the same result (all inconclusive) when I run all tests...

json file (pickledFeatures) saved as txt to be able to upload...

[pickledFeatures.txt](https://github.com/picklesdoc/pickles/files/601616/pickledFeatures.txt)
[TestRapport.txt](https://github.com/picklesdoc/pickles/files/601608/TestRapport.txt)

**Comment by dirkrombauts** [comment]
Thanks for taking the time to report this issue. I should have some time next week to look into it.

**Comment by pisten** [comment]
errr, this 'bug' is due to 'moron behind keyboard' as we say in my country...

I use nunit3, but then stated `--test-results-format=nunit` and `pickles -h` clearly state there is a difference between nunit and nunit3...

**Comment by dirkrombauts** [comment]
Ah well, happens to us all :-) I'm glad you're good to go again!
