### ISSUE TITLE
how to install on Mac

### ISSUE THREAD

**Issue by vikramvi** [picklesdoc/pickles#392]
Hi,

Kindly clarify how to install this tool on Mac.

After reading getting started  got impression that this only runs on Windows. But most of developer and/or QA engineers use Mac.

Please clarify

Thanks,
Vikram

**Comment by dirkrombauts** [comment]
Hi,

You will need to install Mono for Mac first: http://www.mono-project.com/download/#download-mac

Then you can run the command line version of Pickles on a Mac.

**Comment by dirkrombauts** [comment]
Hi,

Do you need more information or can I close this issue?

**Comment by vikramvi** [comment]
Hi @dirkrombauts 

I've installed the s/w on Mac 10.11.6, now to generate html files from feature files do I need to follow unique instructions for Mac or they are same as Windows ?

Thanks,
Vikram

**Comment by vikramvi** [comment]
I tried 
choco install pickles but it failed with error
 -bash: choco: command not found

**Comment by vikramvi** [comment]
also set the path explicitly per http://stackoverflow.com/questions/32542535/mono-installed-on-mac-but-not-recognized-in-terminal, but no success in getting pickles installed yet

**Comment by dirkrombauts** [comment]
Hi,
There's no Choco for Mac as far as I know, so you'll have to download the binaries from the releases page on GitHub: https://github.com/picklesdoc/pickles/releases

If I remember correctly (it's been a while) you need to prefix all calls to pickles.exe with "mono":

    mono pickles.exe ...

**Comment by vikramvi** [comment]
Thanks a ton for quick info. I could run and see some output. 

Will continue exploring this awesome tool and get back with issues / queries.

http://www.mono-project.com/docs/about-mono/supported-platforms/osx/
