### ISSUE TITLE
Error - File name: 'Autofac, Version=4.1.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da'

### ISSUE THREAD

**Issue by vikramvi** [picklesdoc/pickles#396]
I tried below command

`mono Pickles.exe --feature-directory=features/ --output-directory=Pickles-Output/`

features directory has got single .feature file.

It's failing with below error

```
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'Autofac, Version=4.1.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da'
```

**Comment by dirkrombauts** [comment]
Hi,

will try to reproduce this on my mac later this week.

**Comment by vikramvi** [comment]
Thanks @dirkrombauts I googled a lot for this problem but didn't find any solution.
I restarted Mac but it didn't help. 

I think this is related to mono framework and not related to pickles,  as yesterday I could make it run couple of times and later it suddenly stopped working. This happened when I was playing with folders and subfolders , moving around feature files

**Comment by vikramvi** [comment]
@dirkrombauts can you please let me know if you could able to reproduce this problem ?

IMHO majority of engineers across tech industry in US, EU and India use Mac OS as their primary OS, it will be nice if you have more support on this than Windows OS ( which is always buggy and not engineers friendly other than MS employees :) )

May be some sanity test cases for Mac OS explicitly can be of great help.

Thanks in advance, looking forward to get this working in coming days.

Regards,
Vikram

**Comment by dirkrombauts** [comment]
I haven't been able to reproduce this issue yet. I'm doing the best I can with a limited time budget :-)

**Comment by vikramvi** [comment]
thanks for info, please let me know if any info needed from my side

**Comment by dirkrombauts** [comment]
I tried again to reproduce this, but it works on my mac. I'm using the latest Mono version. Pickles works slowly, but it works.

**Comment by vikramvi** [comment]
I will uninstall mono and try again with latest version of Mono and Pickles

**Comment by vikramvi** [comment]
@dirkrombauts I'm still getting the same error, with latest version of pickles as well.

Below is my directory structure on mac, may I'm doing something wrong while executing command please clarify

/Users/vikram-anna/Downloads


Pickles.exe
features/login_stories.feature

mono Pickles.exe --feature-directory=features/ --output-directory=Pickles-Output/

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'Autofac, Version=4.2.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da'

Can you please share your directory structure and any sample feature file you're trying out ?

Thanks in advance & merry x-mas :)

**Comment by vikramvi** [comment]
Just to be safer side, I uninstalled existing version of mono and installed latest version 4.6.2. But no luck.

**Comment by vikramvi** [comment]
@dirkrombauts I really loved if your tool has worked with Mac; as I liked the final output format for living documentation. But sadly it seems to only work with Windows OS. 

I've decided to try out other 2 tools which works well with Mac OS
https://github.com/rmpestano/cukedoctor
https://github.com/burtlo/yard-cucumber

I request you to migrate project to Mac OS based technology as majority of companies use Mac for internal development and usage. As well majority of MSFT employees as well ( I was with MSFT for 1 year ) 

Thanks again.

Kind Regards,
Vikram

**Comment by dirkrombauts** [comment]
@vikramvi I understand your frustration, and thanks for your kind words about the output.

I wish I could accommodate you with Mac OS-based technology, but I just don't have the expertise for that. I don't think I will acquire that expertise in the near future either. I'm sorry.
