### ISSUE TITLE
Getting inconclusive test results in my documentation 

### ISSUE THREAD

**Issue by mhjongerius** [picklesdoc/pickles#419]
Hi guys, I'm trying to get the automated documentation running using Specflow and nUnit3. I use the following test scenario:
Feature: employees
	This is a test

@employees
Scenario: The employees endpoint should be set to employees
	Given I analyse the employees api controller
	When I use the IEnumerable<Employee> Get endpoint
	Then the routing should be correctly set to employees

And run both nUnit and Pickles as post build step:
"$(SolutionDir)packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" "$(TargetPath)"
"$(SolutionDir)packages\Pickles.CommandLine.2.12.0\tools\pickles.exe" --feature-directory="$(ProjectDir)Endpoints" --output-directory="$(ProjectDir)Documentation" --link-result-file="$(TargetPath)TestResult.xml" --documentation-format="DHtml" --test-results-format="nunit3"

I have the testresults file attached:
[TestResult.zip](https://github.com/picklesdoc/pickles/files/748364/TestResult.zip)

For some reason I keep getting the inconclusive result 
<img width="759" alt="knipsel" src="https://cloud.githubusercontent.com/assets/1750238/22558791/454af868-e96f-11e6-90b8-a9fcc5732a0d.PNG">

Feature file: 
[Employees.feature.txt](https://github.com/picklesdoc/pickles/files/748411/Employees.feature.txt)

Any advise on what I'm doing wrong.

**Comment by TheSeleniumGuys** [comment]
Same here, we went through the set up on two machines and are having the same issue of Inconclusive Results and the Pass/Fail flags are not showing at all. Generated TestResults.xml using NUnit.ConsoleRunner.3.6.0. Set-up using latest copy of PicklesUI via Choc, Test Result Format as NUnit 3.

**Comment by mhjongerius** [comment]
I think I found the issue: the link "$(TargetPath)TestResult.xml" is actually returning:
"C:\Projects\CC 2017\Bergler.CC2017.WebAPI.Tests\bin\Debug\Bergler.CC2017.WebAPI.Tests.dllTestResult.xml"

which is off course not the correct path :)

**Comment by mhjongerius** [comment]
I got it operational although I'm not really sure what caused the problem. I decided to download PicklesUI to see if the documentation worked and it did. Finally I modified the post build step to:

"$(SolutionDir)packages\Pickles.CommandLine.2.12.0\tools\pickles.exe" --f="$(ProjectDir)Endpoints" --o="$(ProjectDir)Documentation" --sv="v1" --sn="CC2017" --lr="$(ProjectDir)$(OutDir)TestResult.xml" --df=dHtml --trfmt=nunit3

And finally got working testresults :)

**Comment by dirkrombauts** [comment]
I'm glad you got it working!

**Comment by dirkrombauts** [comment]
@TheSeleniumGuys I will soon publish a new version of Pickles that fixes the problem with NUnit 3 results when using NUnit 3.6

**Comment by ZarkStudios** [comment]
Great! We're using Pickles for our Living Docs so great to see you guys jumping on this so quickly.

**Comment by dirkrombauts** [comment]
@ZarkStudios thank you for your kind words! Please let me know it there's anything I can do to help you.

**Comment by mhjongerius** [comment]
@dirkrombauts you guys are definitely doing a great job very quick responses indeed.

**Comment by dirkrombauts** [comment]
@mhjongerius thank you!

**Comment by dirkrombauts** [comment]
@TheSeleniumGuys I released version [2.13.0](https://github.com/picklesdoc/pickles/releases/tag/v2.13.0) with a fix for the NUnit 3 results.
