### ISSUE TITLE
Wildcards in Test Result Files: Trying to do a pull request, but get a 403 forbidden

### ISSUE THREAD

**Issue by Autom8edChaos** [picklesdoc/pickles#420]
After asking for some help on StackOverflow this morning. I spend a while to get the issue fixed, or better: implement wildcard support. 

But when I perform a pull request, or do a commit-push, I get an 403 forbidden error. The error pops up both in the Visual Studio UI as on the GIT command line.
I changed the protocol of [origin] from https to ssh in the git.config file, but that didn't work either. Do you know how to proceed?

This is the content of the pull request:

> ## Wildcard support for test result files
> 
> Wildcards can be used for testresult files like: 
> C:\results\*.trx 
> or 
> C:\runs\Acceptance*.xml;C:\dev\unit*.xml
> 
> Works in combination with semicolon.
> The wildcard will select multiple files if they match.
> 
> All tests pass, new tests added.
> Commandline use tested in the wild.
> 
> Code is implemented for commandline, powershell, msbuild and for future use in UI*. All other behaviour in these configs is kept the same (like: semicolon use is only implemented for commandline).
> 
> \* UI does a check on the existing of the file before the GENERATE button becomes enabled. This does not work wild wild cards.
> 
> Known Limitations: 
> - does not work when path is empty
> - unknown if relative paths are supported
> - breaks when path does not exist
> 
> Above limited behaviour is not described or tested in the master version, please advice.

**Comment by dirkrombauts** [comment]
Hi,

First of all thanks for your efforts and your time!

Some thoughts:

- Are you perhaps working directly against the picklesdoc repository?
- Your fork of Pickles looks really old. You should rebase against the develop branch of the picklesdoc repository
- Can you push to your other repositories?

**Comment by Autom8edChaos** [comment]
- Are you perhaps working directly against the picklesdoc repository?
No, I don't think so my path under my repos is repos\pickles

- Your fork of Pickles looks really old. You should rebase against the develop branch of the picklesdoc repository
Yeah, that was a really old one, I should delete it. But that is not the one I am working on. I imported it straight into Visual Studio through this page: https://github.com/picklesdoc/pickles via the Download > Open in Visual Studio option.

- Can you push to your other repositories?
Yes, I can commit-and-push from VS into an owned project, see: https://github.com/Autom8edChaos/SnelRekenen-FB1

**Comment by dirkrombauts** [comment]
OK, that clears it up. The fact that your imported in into VS through  https://github.com/picklesdoc/pickles means that you are in fact trying to push directly to the picklesdoc repository.

I think the easiest way is to do the following:

- Delete your old pickles repository on github
- Fork the pickles repository (so that you have a new pickles repository)
- Load that into visual studio
- make your changes there
- push to github
- create a pull request

Hope that helps.

**Comment by Autom8edChaos** [comment]
Yes, it worked. As you noticed, I am quite new to the whole GitHub flow. Watched the howto videos, but those are so verbose, it is easy to look over the important parts :).

**Comment by dirkrombauts** [comment]
You seem to be doing well with catching up. Keep up the good work!
