### ISSUE TITLE
The CucumberJS output format seems to omit examples of scenario outlines

### ISSUE THREAD

**Issue by dirkrombauts** [picklesdoc/pickles#428]

**Comment by jnsn** [comment]
Any update on this?

**Comment by dirkrombauts** [comment]
No, no update on this.

**Comment by jnsn** [comment]
I've looked into this a bit further, but there seems to be something off with the official documentation.

According to https://relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter#scenario-outline the examples should be included into a single scenario outline, however, if I run this using the ruby cucumber exporter I get multiple tests. Each described as an individual scenario, but of course with the same scenario name.

Attached are a feature file and the resulting output.

`$  cucumber --format json > output.txt`

[sample.feature.txt](https://github.com/picklesdoc/pickles/files/1778520/sample.feature.txt)
[output.txt](https://github.com/picklesdoc/pickles/files/1778518/output.txt)

I could create a PR for this, as it's not to difficult to implement I think, but I was wondering which output format you would prefer. The one with the examples? Or the one with each scenario outline as a single element?

**Comment by dirkrombauts** [comment]
I will welcome a PR. Please go for the Cucumber variant - that is what is happening in the real world. Relish is abandoned (sadly) so their documentation may well be out of date.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
