### ISSUE TITLE
pickles.exe can't take path with spaces from cmd

### ISSUE THREAD

**Issue by Rain9333** [picklesdoc/pickles#429]
You can't provide any path (output, feature or xml) if there is spaces in it. You also can't escape it but putting it in quotes like you usually do with running program from command prompt. Which leads to limitation...

**Comment by DominikBaran** [comment]
@Rain9333 : hello Rain9333 - it works perfectly fine for me - to run Pickles.CommandLine i used:

--feature-directory="C:\Dev\TestProject\Tests\Features" -o="C:\Dev\TestProject\Documentation with spaces" -trfmt=xunit2 -lr="C:\Dev\TestProject\Reports new\report.xml" -df=dhtml

My OS is Win10. Can you please send an example of your cmd line command.

**Comment by dirkrombauts** [comment]
@Rain9333 is this still a problem for you?

**Comment by Rain9333** [comment]
@dirkrombauts @DominikBaran - yes still applicable for me.
Not sure if its the quotes or something but notice that the issue appear whenever I have spaces or not in the path, but I put the path in quotes.

E.g. (both failing - of course I change the folder names before executing them so they are correct and existing 😃 ): 
`pickles.exe -df=dhtml -trfmt=nunit3 -f=C:\Tests\Features\ -o="C:\Testme2\" -lr="C:\Testme\Result.xml" -exp`
&
`pickles.exe -df=dhtml -trfmt=nunit3 -f=C:\Tests\Features\  -o="C:\Test me 2\" -lr="C:\Test me\Result.xml" -exp`

Error is:
```
Unhandled Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at System.IO.Abstractions.DirectoryInfoFactory.FromDirectoryName(String directoryName)
   at PicklesDoc.Pickles.CommandLine.CommandLineArgumentParser.Parse(String[] args, IConfiguration configuration, TextWriter stdout) in C:\Dev\Code\GitHub\PicklesDoc\pickles\src\Pickles\Pickles.CommandLine\CommandLineArgumentParser.cs:line 111
   at PicklesDoc.Pickles.CommandLine.Program.Main(String[] args) in C:\Dev\Code\GitHub\PicklesDoc\pickles\src\Pickles\Pickles.CommandLine\Program.cs:line 40
```

I tried with v2.16.2 & with Pickles-exe-2.18.0.zip from here https://github.com/picklesdoc/pickles/releases
OS: Windows 10 Pro x64 latest updates

![pickles](https://user-images.githubusercontent.com/25606664/36022750-c95998ba-0d92-11e8-8184-307ad8050779.png)

Note: This is the only way I make it work (no spaces in the path and no quotes):
`pickles.exe -df=dhtml -trfmt=nunit3 -f=C:\Tests\Features\ -o=C:\Testme2\ -lr=C:\Testme\Result.xml -exp`

**Comment by DominikBaran** [comment]
@Rain9333 : 
hello - looks like Pickles command line has some issues with the "\" at the end of the paths.
Can you please try:
pickles.exe -df=dhtml -trfmt=nunit3 -f=C:\Tests\Features -o="C:\Testme2" -lr="C:\Testme\Result.xml" -exp 
instead of: pickles.exe -df=dhtml -trfmt=nunit3 -f=C:\Tests\Features\ -o="C:\Testme2\" -lr="C:\Testme\Result.xml" -exp

Please let me know how it looks like

**Comment by Rain9333** [comment]
Hey @DominikBaran and thanks for the help!

Here are my results and thanks for the info from that blog as well:

`pickles.exe -df=dhtml -trfmt=nunit3 -f=C:\Tests\Features\ -o="C:\Test me 2" -lr="C:\Test me\Result.xml" -exp`   (**working ->  -o="C:\Test me 2"** )
`pickles.exe -df=dhtml -trfmt=nunit3 -f=C:\Tests\Features\ -o="C:\Test me 2\" -lr="C:\Test me\Result.xml" -exp`   (**same error as before ->  -o="C:\Test me 2\\"**)
`pickles.exe -df=dhtml -trfmt=nunit3 -f=C:\Tests\Features\ -o="C:\Test me 2\\" -lr="C:\Test me\Result.xml" -exp`   (**working ->  -o="C:\Test me 2\\\\"**) 

Hopefully this will make it easier on the next guys as well (wonder if it's worth it to be documented somehow. - Issue can be closed, thanks again Dominik!

**Comment by DominikBaran** [comment]
@Rain9333 :  that's great to hear, at least we know the issue and the reason now :)
@dirkrombauts : I agreed with @Rain9333  - so maybe it's worth to add it to the documentation.

Cheers,
D

**Comment by dirkrombauts** [comment]
I wrote a wiki page about this issue: https://github.com/picklesdoc/pickles/wiki/Backslashes-and-quotes-at-the-end-of-a-path
