### ISSUE TITLE
Writing excel workbook throws exception

### ISSUE THREAD

**Issue by chaswiso** [picklesdoc/pickles#431]
![2017-02-10_14-07-34](https://cloud.githubusercontent.com/assets/2489731/22842359/89349800-ef9a-11e6-96b7-8949fcb1b03a.png)

**Comment by dirkrombauts** [comment]
Hi,

Thank you for taking the time to report this.

- I released a new version of Pickles yesterday (version 2.13.0). If you are using an older version, could you please try the newest version?
- Does the problem occur only when you use the Excel output format or does it occur in other output formats as well?

**Comment by chaswiso** [comment]
I have an older version of picklesui (will need to check which one) which worked for months and this week I started to get the error. 
I download 2.13 from choclatey and got he same error. So now I'm wondering what outside app might be messing with it?
Excel is the only one giving me that error. Btw I couldn't find the picklesui.exe in 2.13. Does it only run from visual studio?

--Chris

**Comment by dirkrombauts** [comment]
The easiest way to obtain picklesui is through chocolatey: https://chocolatey.org/packages/picklesui . If you don't have chocolatey, the next easiest method is to download it from the release page on GitHub: https://github.com/picklesdoc/pickles/releases.

You don't need visual studio to run Pickles.

Does the error happen if you try different feature files as well? Or only on your set?

**Comment by chaswiso** [comment]
I'll run for individual folders and see if any have success. 
Thank you for the links! I love the app and really appreciate your quick response 

--Chris

**Comment by chaswiso** [comment]
Hi Dirk
I'm back in business. Found one line Feature: that was blank. Excel gets generated for all files now. 

Here's a different issue though. I'll log it in github. When you close out picklesui, I get a PicklesUI has stopped working. 

Takes a couple of clicks of close the program to make it go away. 
Also. Your settings are not saved like filepath etc. 

--Chris

**Comment by chaswiso** [comment]
Downloaded from /releases and it all worked perfectly!
Thanks for 2.13!!

--Chris

**Comment by dirkrombauts** [comment]
I'm glad you got it working!

Can we close this issue?

**Comment by chaswiso** [comment]
Yes
Thanks Dirk. Please mark as not a defect 

--Chris
