### ISSUE TITLE
Ignored scenarios are reported as Inconclusive

### ISSUE THREAD

**Issue by Rain9333** [picklesdoc/pickles#436]
Why my nunit3 ignored test scenarios (SpecFlow) are reported as Inconclusive? Is this the expected behavior?

![results](https://cloud.githubusercontent.com/assets/25606664/23057189/ab4672d0-f4f7-11e6-8b89-8f3a15deb31b.jpg)

**Comment by dirkrombauts** [comment]
Hi,

Yes, this is the expected behaviour. Pickles uses only three outcomes for a scenario: Pass, Fail, everything else is Inconclusive.

**Comment by Rain9333** [comment]
Thank you. Didn't found the answer of that anywhere - will close the issue!
