### ISSUE TITLE
Keyword "Examples" is not localized

### ISSUE THREAD

**Issue by andreheijstek** [picklesdoc/pickles#439]
Hi (and thanks for a very useful tool),

I am creating my Gherkins in Dutch (#language nl-NL) and most of that is shown correctly in Pickles.
However my Examples (in Scenario Outlines) are displayed as "Examples" and not as "Voorbeelden".

**Comment by dirkrombauts** [comment]
Is only the examples section in English and are the other keywords in Dutch? Could you perhaps post a screenshot?

Which output format do you use?

**Comment by andreheijstek** [comment]
Hello Dirk,

Everything is in Dutch, except the keyword ‘Examples’. I can send a screenshot on Thursday.
Output format is HTML

Regards, André

**Comment by dirkrombauts** [comment]
Did you try it with the other output formats too? What is the result there?

**Comment by dirkrombauts** [comment]
I can reproduce the problem on my system. It happens in the HTML, DHTML, Word and Excel output formats. The other two are not affected since they are json-based and thus don't need localization.

**Comment by dirkrombauts** [comment]
@andreheijstek no need to send me a screenshot anymore :-)

**Comment by dirkrombauts** [comment]
I'll release a new version next week. If you're impatient you can always check out the latest code and build Pickles yourself ;-)

**Comment by andreheijstek** [comment]
Cool, thanks for picking it up so fast!
