### ISSUE TITLE
Support codepage 1252 / iso-8859-1 encoding

### ISSUE THREAD

**Issue by lars-erik** [picklesdoc/pickles#447]
Currently when trying to generate docs based on feature files saved with Western European encoding (codepage 1252 / iso-8859-1, the cmdlet and commandline tools just exits quietly as if success. In reality, there's parse errors due to all the Scandinavian characters. They've not been read with the right encoding, so all the special chars are weird blocks and crap.

Using signed UTF-8 files work, but it would be nice not having to change it for all files.

**Comment by dirkrombauts** [comment]
Hi,

The newest version of Pickles (2.15, released yesterday) should at least exit with an error. Could you please verify that this is the case?

As for the encoding issue itself: at the moment I don't know what to do about it. Do you know of a method to detect the encoding of a file?

**Comment by lars-erik** [comment]
I'm out of my league when it gets to encodings. :) Had to give it a shot though, so a suggestion was just PR'd. It's very little intrusive, but I can't get it harnessed using the mock file system. It messes up the encoding. *facepalm* :)

Have a look at it. The plan was to generalize the test and pass several files as test cases.

**Comment by dirkrombauts** [comment]
Maybe you could use a tool like [UTFCast](https://www.rotatingscrew.com/utfcast-express.aspx) to batch convert all your files to UTF-8?

**Comment by lars-erik** [comment]
It happened because I created a few files with notepad. VS creates them as UTF8, and I know how to change them. So few I didn't need to automate. Thanks none-the-less. :)
So as mentioned on the PR, there's no rush, but can't hurt.

**Comment by dirkrombauts** [comment]
As I said in the PR, I will keep the current behaviour because UTF-8 is constant - Encoding.Default is potentially different for everyone.

**Comment by lars-erik** [comment]
Thanks for triaging it. It'd do UTF-8 when the files are UTF-8, but I get your point. Better safe than sorry-ish. I'll just make sure not to create ASCII files in explorer. :)
