### ISSUE TITLE
DHTML/Nunit3  version does not show the Pass/Failed example status 

### ISSUE THREAD

**Issue by lagori** [picklesdoc/pickles#451]
?Using the format as DHTML and using the results from Nunit3 xml the example individual status  (pass or fail) not shown. If used with the HTML format its shown. Attaching the results, and HTML and DHTML screenshots
[SS.zip](https://github.com/picklesdoc/pickles/files/881818/SS.zip)

**Comment by dirkrombauts** [comment]
I assume you are talking about the results of individual examples in a scenario outline.

This is a known limitation of the dhtml format. There's a pull request in the works that provides base functionality that will enable us to fix the limitation.

Please have a look at the PR if you think you can contribute.

**Comment by younggeezus** [comment]
@dirkrombauts I am having the same issue also. I have seen this question asked very recent and very often on Google without resolution.

**Comment by dirkrombauts** [comment]
@younggeezus is your issue about the results of individual examples in a scenario outline in the DHTML version only, or does your problem occur in other output versions too?

**Comment by younggeezus** [comment]
@dirkrombauts thanks for the quick response. It is happening in all the output versions

**Comment by dirkrombauts** [comment]
Which version of Pickles and of NUnit are you using?

**Comment by younggeezus** [comment]
I am using Pickles v2.15.0 which I installed with Poweshell and the NUnit I am using is the 3.6.1

**Comment by dirkrombauts** [comment]
Could you provide me with a sample project that shows the problem? That will really speed up my investigation.

**Comment by younggeezus** [comment]
What is your email address please? So I can email it to you

**Comment by dirkrombauts** [comment]
dirk dot rombauts at picklesdoc dot com

**Comment by dirkrombauts** [comment]
@younggeezus are you still experiencing this problem?

**Comment by dirkrombauts** [comment]
@younggeezus I'm closing this issue since I haven't heard anything from you for at least two months. Feel free to reopen the issue if you are still experiencing the problem.
