### ISSUE TITLE
Exclude Feature Files that have no included scenarios

### ISSUE THREAD

**Issue by dirkrombauts** [picklesdoc/pickles#453]
When using the `excludeTags` parameter, it may happen that all scenarios of a feature file are excluded. When that happens, the feature file should not be included in the generated living documentation, nor should it appear in the table of content.

**Comment by joelransom** [comment]
Hi Dirk. By any chance did this ever get implemented in any release after 2.15.0? 

Regards, 

Joel

**Comment by dirkrombauts** [comment]
No, there has been no progress on this one. I'll be happy to review any Pull Requests you may send my way :-)

**Comment by kwlin** [comment]
Question about this issue & merged pulled request #529 

We have feature files without any scenario's. This kind of feature files are more a description about a feature. 

The older version of pickles (like 2.18) will generate living docs with this feature file, but since 2.19 the feature is not in the living docs/output anymore. Can we bypass this option/feature of pickles?

**Comment by dirkrombauts** [comment]
Hi,

No, you cannot bypass this feature of Pickles.

There is an alternative way to include your descriptions in pickles. Are you familiar with MarkDown? You can include MarkDown files, and Pickles will render them. The easy, works-90%-of-the-times way is to rename your `feature-file-without-scenario.feature` to `feature-file-without-scenario.md`.

Does that help you?

**Comment by kwlin** [comment]
Thnx for the alternative way! I'll try it out asap

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
