### ISSUE TITLE
Ability to add manual test checkboxes to HTML doc

### ISSUE THREAD

**Issue by frankdoylezw** [picklesdoc/pickles#455]
One of our use-cases for Pickles is to generate manual test scripts for the Test Analysts in our team. 

We use Specflow feature files as manual test cases, initially, and then slowly but surely add bindings to convert these to automated test cases. Whilst using the Specflow feature files as manual test cases, it would be useful to be able to mark each scenario as Passed/Failed using a checkbox or similar. This would then allow us to simply send the Picklesdoc html file to the Product Owner as a record of testing completed.

Our issue: We can add a simple checkbox to the generated html (see attached), but obviously the checkmark doesn't persist. 

Is this something that could possibly be added?
![pickles](https://cloud.githubusercontent.com/assets/8546048/25127953/d16a7e7c-242f-11e7-89de-35f0251fa340.jpg)

**Comment by dirkrombauts** [comment]
Hi,

Pickles is primarily a living documentation generator, not a test reporting tool. For that reason, I am not keen on adding this feature.

You might be able to work around this limitation: Pickles can take multiple test results as input. What you can try: use your test runner to execute all scenarios that do not have bindings yet. The resulting file will be completely inconclusive. Edit this file by hand with the results of the manual verification. Provide the edited file to Pickles, together with an result file of all the scenarios that have bindings. It's best to keep scenarios with unbound steps out of this second result file: I don't know what Pickles does when multiple result files provide a result for the same scenario.

**Comment by dirkrombauts** [comment]
As I said before, pickles is a living documentation generator. For that reason, I will not add this feature.
