### ISSUE TITLE
Not seeing my test results using Pickles UI

### ISSUE THREAD

**Issue by deepthikarthikeyan** [picklesdoc/pickles#461]
I'm using pickles UI to view some test reports generated from specflow. I can see the feature files but not the results.
When I open the test results.xml, I can view the test results .But when I open through GUI no result information is displayed.

A peek at testresults.xml

<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="95" result="Failed" total="95" passed="93" failed="2" inconclusive="0" skipped="0" asserts="0" engine-version="3.6.1.0" clr-version="4.0.30319.42000" start-time="2017-05-19 19:57:55Z" end-time="2017-05-19 20:01:31Z" duration="215.922428">
  <command-line><![CDATA[nunit3-console.exe  C:\CMSTestAutomation\testautomation\WebServiceCalls\bin\Debug\WebServiceCalls.dll]]></command-line>
  <test-suite type="Assembly" id="0-1110" name="WebServiceCalls.dll" fullname="C:\CMSTestAutomation\testautomation\WebServiceCalls\bin\Debug\WebServiceCalls.dll" runstate="Runnable" testcasecount="95" result="Failed" site="Child" start-time="2017-05-19 19:57:55Z" end-time="2017-05-19 20:01:30Z" duration="215.037847" total="95" passed="93" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="0">
    <environment framework-version="3.6.1.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 6.3.9600.0" platform="Win32NT" cwd="C:\NUnit.Console-3.6.1" machine-name="WIN-4CPVLLN519L" user="Administrator" user-domain="WIN-4CPVLLN519L" culture="en-US" uiculture="en-US" os-architecture="x64" />
    <settings>
      <setting name="DisposeRunners" value="True" />
      <setting name="WorkDirectory" value="C:\NUnit.Console-3.6.1" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.5.2" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="2" />
    </settings>
    <properties>
      <property name="_PID" value="10644" />
      <property name="_APPDOMAIN" value="domain-" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="0-1111" name="WebServiceCalls" fullname="WebServiceCalls" runstate="Runnable" testcasecount="95" result="Failed" site="Child" start-time="2017-05-19 19:57:55Z" end-time="2017-05-19 20:01:30Z" duration="215.013513" total="95" passed="93" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="0">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestSuite" id="0-1112" name="Features" fullname="WebServiceCalls.Features" runstate="Runnable" testcasecount="95" result="Failed" site="Child" start-time="2017-05-19 19:57:55Z" end-time="2017-05-19 20:01:30Z" duration="215.009530" total="95" passed="93" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="TestFixture" id="0-1010" name="EvaluateTheCampaignManagementWebserviceFeature" fullname="WebServiceCalls.Features.EvaluateTheCampaignManagementWebserviceFeature" classname="WebServiceCalls.Features.EvaluateTheCampaignManagementWebserviceFeature" runstate="Runnable" testcasecount="90" result="Passed" start-time="2017-05-19 19:57:55Z" end-time="2017-05-19 20:00:48Z" duration="172.589342" total="90" passed="90" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="0">
          <properties>
            <property name="Description" value="Evaluate the Campaign Management Webservice" />
          </properties>

**Comment by deepthikarthikeyan** [comment]
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="95" result="Failed" total="95" passed="93" failed="2" inconclusive="0" skipped="0" asserts="0" engine-version="3.6.1.0" clr-version="4.0.30319.42000" start-time="2017-05-19 19:57:55Z" end-time="2017-05-19 20:01:31Z" duration="215.922428">
  <command-line><![CDATA[nunit3-console.exe  C:\CMSTestAutomation\testautomation\WebServiceCalls\bin\Debug\WebServiceCalls.dll]]></command-line>
  <test-suite type="Assembly" id="0-1110" name="WebServiceCalls.dll" fullname="C:\CMSTestAutomation\testautomation\WebServiceCalls\bin\Debug\WebServiceCalls.dll" runstate="Runnable" testcasecount="95" result="Failed" site="Child" start-time="2017-05-19 19:57:55Z" end-time="2017-05-19 20:01:30Z" duration="215.037847" total="95" passed="93" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="0">
    <environment framework-version="3.6.1.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 6.3.9600.0" platform="Win32NT" cwd="C:\NUnit.Console-3.6.1" machine-name="WIN-4CPVLLN519L" user="Administrator" user-domain="WIN-4CPVLLN519L" culture="en-US" uiculture="en-US" os-architecture="x64" />
    <settings>
      <setting name="DisposeRunners" value="True" />
      <setting name="WorkDirectory" value="C:\NUnit.Console-3.6.1" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.5.2" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="2" />
    </settings>
    <properties>
      <property name="_PID" value="10644" />
      <property name="_APPDOMAIN" value="domain-" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="0-1111" name="WebServiceCalls" fullname="WebServiceCalls" runstate="Runnable" testcasecount="95" result="Failed" site="Child" start-time="2017-05-19 19:57:55Z" end-time="2017-05-19 20:01:30Z" duration="215.013513" total="95" passed="93" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="0">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestSuite" id="0-1112" name="Features" fullname="WebServiceCalls.Features" runstate="Runnable" testcasecount="95" result="Failed" site="Child" start-time="2017-05-19 19:57:55Z" end-time="2017-05-19 20:01:30Z" duration="215.009530" total="95" passed="93" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="TestFixture" id="0-1010" name="EvaluateTheCampaignManagementWebserviceFeature" fullname="WebServiceCalls.Features.EvaluateTheCampaignManagementWebserviceFeature" classname="WebServiceCalls.Features.EvaluateTheCampaignManagementWebserviceFeature" runstate="Runnable" testcasecount="90" result="Passed" start-time="2017-05-19 19:57:55Z" end-time="2017-05-19 20:00:48Z" duration="172.589342" total="90" passed="90" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="0">
          <properties>
            <property name="Description" value="Evaluate the Campaign Management Webservice" />
          </properties>

**Comment by dialex** [comment]
Maybe this one is related?
https://github.com/picklesdoc/pickles/issues/460

**Comment by dirkrombauts** [comment]
@deepthikarthikeyan could you please provide some more details? A screenshot from the Pickles UI, and if possible your feature files and test result file.

**Comment by dirkrombauts** [comment]
@deepthikarthikeyan I'm closing this issue since there hasn't been any activity for a long time. Feel free to reopen it if this issue is still important to you.
