### ISSUE TITLE
Pickles cannot deal with languages that have a hyphen in the name

### ISSUE THREAD

**Issue by barlino** [picklesdoc/pickles#478]
According to the supported gherkin-languages,
https://github.com/cucumber/gherkin-dotnet/blob/master/Gherkin/gherkin-languages.json#L2097

only support language "nl".

After consulting the source code, I found language nl-be was added.
In that scenario, I run into a issue which is that can not distinguish with zh-TW and zh-CN.

Due to #386, it split the language code into the first word if contains '-'. but zh is not known by  GherkinDialectProvider.

Here is the console output as follow

> Pickles did not complete successfully Language not supported: zh

Could it be possible to full support the gherkin-languages?

**Comment by dirkrombauts** [comment]
I think I see the problem - the GherkinDialectProvider just blindly splits the language if there's a '-', without checking if the name with the hyphen is a valid language first. I'll need to first try if the language is recognized, and split only if it was not recognized.

Could you perhaps provide me with a sample feature file in zh language? I'm afraid I don't have experience with Chinese ...

**Comment by barlino** [comment]
[zh-CN.feature.txt](https://github.com/picklesdoc/pickles/files/1202460/zh-CN.feature.txt)
[zh-TW.feature.txt](https://github.com/picklesdoc/pickles/files/1202461/zh-TW.feature.txt)

Sure, Here comes zh-CN and zh-TW feature smaples as attachments

**Comment by dirkrombauts** [comment]
Hi,
I think I fixed the problem. Could you take a look at the branch where I fixed the problem and see if it solves your problem? It works with the two feature files you sent me, at any rate.

https://github.com/dirkrombauts/pickles/tree/language-with-hyphen

**Comment by barlino** [comment]
Yes, now the DialectProvider can know the whole gherkin-languages as well. thanks

**Comment by dirkrombauts** [comment]
Released in version [2.16.1](https://github.com/picklesdoc/pickles/releases/tag/v2.16.1).
