### ISSUE TITLE
While exporting to excel, trim the worksheet names if feature file names have more than 31 characters

### ISSUE THREAD

**Issue by pawarvaibhav** [picklesdoc/pickles#481]

**Comment by pawarvaibhav** [comment]
Currently, we face this error if any of the included feature file names have more than 31 characters

Something went wrong during generation: System.ArgumentException: Worksheet names cannot be more than 31 characters
  at ClosedXML.Excel.XLWorksheet.set_Name (System.String value) [0x00000] in <filename unknown>:0 
  at ClosedXML.Excel.XLWorksheet..ctor (System.String sheetName, ClosedXML.Excel.XLWorkbook workbook) [0x00000] in <filename unknown>:0 
  at ClosedXML.Excel.XLWorksheets.Add (System.String sheetName) [0x00000] in <filename unknown>:0 
  at ClosedXML.Excel.XLWorkbook.AddWorksheet (System.String sheetName) [0x00000] in <filename unknown>:0 
  at PicklesDoc.Pickles.DocumentationBuilders.Excel.ExcelDocumentationBuilder.Build (PicklesDoc.Pickles.DataStructures.Tree features) [0x00000] in <filename unknown>:0 
  at PicklesDoc.Pickles.Runner.Run (IContainer container) [0x00000] in <filename unknown>:0  Worksheet names cannot be more than 31 characters
Pickles did not complete successfully Worksheet names cannot be more than 31 characters

**Comment by pawarvaibhav** [comment]
There is a chance that while trimming longer names to 31 characters, we might end up with duplicate names. That would mean another error with duplicate names for worksheets.

To avoid that, we can trim the name in the following fashion:
Take 15 characters from the start of the file name and 16 characters from the end of the file name. I believe, that way, there is a smaller chance of ending with duplicate names.

**Comment by dirkrombauts** [comment]
Good idea. It would be great if you could provide a pull request with this change and some unit tests for it. That's the fastest way to get it included.

**Comment by pawarvaibhav** [comment]
I have not worked on any C# projects since college. I tried to look at your project but the framework is a lot different than what I am used for test frameworks in TestNG and Java. 

Does your framework have a name? so that I can research online and try to fix this.

**Comment by jonathanbass** [comment]
Should this issue be closed now?
I was prepared to fix this but it looks like it has [https://github.com/picklesdoc/pickles/blob/develop/src/Pickles/Pickles.DocumentationBuilders.Excel/ExcelSheetNameGenerator.cs#L34](already been implemented)

**Comment by pawarvaibhav** [comment]
This solution will cause errors if the feature names are long and similar to one another - For e.g.
Feature1: FeatureNameLongerThanThirtyOneCharacters.feature
Feature2: FeatureNameLongerThanThirtyOneNumbers.feature

In this case, I believe pickles would throw an error coz, it trimmed both file names and 2 worksheets will end up having the same name.

**Comment by dirkrombauts** [comment]
@jonathanbass as far as I understand it, this issue is still open - for the reasons mentioned by @pawarvaibhav . You are very welcome to fix it :-)

**Comment by jonathanbass** [comment]
Ah, okay sure. I understand now.

So what would we like the actual fix to do if the names are the same according to the first 31 characters?

Increment a numeric suffix?

**Comment by jonathanbass** [comment]
Actually @dirkrombauts and @pawarvaibhav if you see [https://github.com/picklesdoc/pickles/blob/develop/src/Pickles/Pickles.DocumentationBuilders.Excel/ExcelSheetNameGenerator.cs#L41](here) this will append a number in brackets if the sheet name already exists.
It is fully unit tested too.

So I am pretty sure we can close this :)

**Comment by dirkrombauts** [comment]
@pawarvaibhav your comments? Do you still experience the problem? If so, could you please provide a sample that demonstrates the error?

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
