### ISSUE TITLE
Custm Buildstep for VSTS builds

### ISSUE THREAD

**Issue by s991116** [picklesdoc/pickles#482]
This is not and Issue, but a nice to have.
For VSTS Builds (TFS-Builds) , it would be nice to have a custom buildstep, that generated documentation with PicklesDoc. This Buildstep could be shared on [VSTS MarketPlace](https://marketplace.visualstudio.com/search?target=vsts&category=Build%20and%20release&sortBy=Downloads)

Now I have a custom powershell script, that calls PicklesDoc.
But if it was a custom buildstep, input to PicklesDoc would be text-inputboxes.
The Custom buildstep will be shared on VSTS Marketplace for everyone to use.

**Comment by dirkrombauts** [comment]
Hi,
I agree that this sounds cool. The reality of open source projects is that they depend on outside contributions. Another reality is that I have a limit time budget - I've already spent rather more than usual on fixing the problem with the test results.

So the fastest way to get a new feature like this is to implement it yourself and to send a pull request.

Thanks for your understanding.

**Comment by s991116** [comment]
I am trying to implement this myself, but I'm wondering if it is something that couold be shared on PicklesDoc, so others can use it.
I will do a pull request, if/when I have something.

**Comment by tedvanderveen** [comment]
Great idea @s991116, do you have a PR yet, maybe I can contribute to your development work?

**Comment by s991116** [comment]
No, unfortunately I do not.
I hadn't have the time to look into it.
Today we are using a powershell script, that retrieve Pickles Doc as a Nuget package.

**Comment by mmajcica** [comment]
Guys, I do have the extension already. I was wandering here https://github.com/picklesdoc/pickles/issues/525
if I am legally allowed to publish it publically.

**Comment by mmajcica** [comment]
I published a Pickles extension on VSTS marketplace, further testing and feedback would be welcome.
https://marketplace.visualstudio.com/items?itemName=mmajcica.PicklesGenerator

**Comment by dirkrombauts** [comment]
Thanks! I announced it on Twitter.
