### ISSUE TITLE
Tags not recognized 

### ISSUE THREAD

**Issue by jabumeri** [picklesdoc/pickles#484]
Hi! I'm experiencing some issues with Pickles at the moment. I've been using the GUI version and for some reason certain tags are not being recognized from within my feature file. I've been generating a DHTML and upon searching for a specific tag, not all of the results are shown. 
We've noticed an odd pattern, some tags that are part of specific examples cannot be found. But please not that this is not a definitive statement, some are found! 

An example of this would be: 

Scenario Outline: ""
@tag_example
Examples: 
| x | y | 
| 1 | 2 |

Any help would be greatly appreciated thanks!

**Comment by dirkrombauts** [comment]
Hi,

I'm afraid I'm going to need more specific information. In the ideal case I'd like to be able to try it myself. Could you please zip your DHTML documentation and either attach it to this issue or send it by email to dirk dot rombauts at picklesdoc dot com? Thanks!

**Comment by jabumeri** [comment]
actually we figured out a work around to our issue! thank you!
