### ISSUE TITLE
PowerShell Runner Shows Only First Test Result File

### ISSUE THREAD

**Issue by boris779** [picklesdoc/pickles#485]
If you add more that one to option _lr_ only the first file is listed in the output when useing the Pickles Command Line Tool.

See my example output. I added 2 json-files but in the output vom commandline tool only the first is listed.

`PS C:\temp\aggregate_cucumber> C:\Programs\nuget\Pickles.CommandLine.2.16.2\tools\pickles.exe -f=C:\temp\features
\pickles --trfmt=cucumberjson --lr='**.\cucumber_1.json;.\cucumber_2.json**' -l=de --df=dhtml --sn=Name --et=ignore
Pickles v.2.16.2.0

Generating documentation based on the following parameters
----------------------------------------------------------
Feature Directory              : C:\temp\features
Output Directory               : c:\temp\pickles
Project Name                   : Name
Project Version                :
Language                       : de
Incorporate Test Results?      : Yes
Include Experimental Features? : No
Exclude Tag                    : ignore
Test Result Format        : CucumberJson
Test Result File          : **C:\temp\aggregate_cucumber\cucumber_1.json**
Writing DHTML files to c:\temp\pickles
Pull Down Feature Images
Write Resources
Utilize JsonBuilder To Dump Json Feature File Next To Dthml Resources
Writing JSON to c:\temp\pickles
Tweak Json file
Pickles completed successfully
PS C:\temp\aggregate_cucumber>`

**Comment by dirkrombauts** [comment]
Thanks!

This is only a problem with displaying the name of the test result file, right? Can you confirm that both of your test result files are being used?

**Comment by boris779** [comment]
Exactly. The result is correct, both files are processed!
Only a display bug :-)

**Comment by dirkrombauts** [comment]
Cool.

The fastest way to get the fix is to send me a pull request :-)

**Comment by dirkrombauts** [comment]
Released in version [2.17.0](https://github.com/picklesdoc/pickles/releases/tag/v2.17.0).
