### ISSUE TITLE
Comments not showing

### ISSUE THREAD

**Issue by francisco4challenge** [picklesdoc/pickles#489]
Hi, i have a .feature file that has comments in multiple lines, and they are not showing up in the generated word file.

I've tried with picklesui, andthe command line exe, in -v 2.16.2 and 2.16.0, both with no luck

i enabled the flag for comments.
Thanks in advance

**Comment by dirkrombauts** [comment]
Could you perhaps post the feature file? If the actual feature file contains your intellectual property, then please anonymize it.

**Comment by francisco4challenge** [comment]
this is the feature file:
#language: pt

Funcionalidade: Ver em que pagamento está contido um num comercial 
    Para poder saber qual a ordem de relativo a um certo num comercial 
    Como staff do departamento financeiro
    Quero poder ver a que está associado num comercial 

#Critérios de aceitação
#Os movimentos que já têm pagamento associado devem ficar com um highligh verde e ter um botão "Ver pagamento".
#Os movimento que não têm pagamento associado devem ficar com um highligh vermelho.
#Um movimento têm um pagamento associado se existir um pagamento com.

Cenário: Indicador visuais dos movimentos segundo terem pagamentos associados ou não.
  Dados os movimentos com os seguintes oooohId:
    |           oooohId                |
    |    00000000000000000000000000    |
    |    00000000000000000000000000    | 
    |    00000000000000000000000000    | 
    |    00000000000000000000000000    |
    |    00000000000000000000000000    | 
    |    00000000000000000000000000    | 
  E os pagamentos com os seguintes oooohId:
    |           oooohId                |
    |    00000000000000000000000000    |
    |    00000000000000000000000000    |
    |    00000000000000000000000000    |
  Quando o --- cruza movimentos com pagamentos
  Então os movimentos com os seguintes oooohId devem ter os seguintes indicadores visuais
    |                oooohId               | Highlight    | 
    |      00000000000000000000000000      |   Verde      | 
    |      00000000000000000000000000      |   Verde      | 
    |      00000000000000000000000000      |   Vermelho   |
    |      00000000000000000000000000      |   Vermelho   |
    |      00000000000000000000000000      |   Verde      | 
    |      00000000000000000000000000      |   Verde      | 

 Cenário: Ver pagamento de um movimento que tenha sido cruzado com sucesso
 Dados os movimentos com os seguintes oooohId:
    |              oooohId             |
    |    00000000000000000000000000    |
    |    00000000000000000000000000    | 
    |    00000000000000000000000000    |
    |    00000000000000000000000000    | 
    |    00000000000000000000000000    | 
  E os pagamentos com os seguintes oooohId:
    |             oooohId              |
    |    00000000000000000000000000    |
    |    00000000000000000000000000    |
    |    00000000000000000000000000    |
  Quando o Bob cruza movimentos com pagamentos
  E vai ver o pagamento associado ao movimento com "00000000000000000000000000"
  Então o Bob deve ver um pagamento com o oooohId "00000000000000000000000000"


The comments dont show up on the word file.

**Comment by dirkrombauts** [comment]
Thanks - I'll have a look at it tonight.

In the meantime, Could you please verify that Generation works if you delete the comments?

**Comment by francisco4challenge** [comment]
I tried it, and it works without the comments

Em 04/10/2017 2:26 da tarde, "Dirk Rombauts" <notifications@github.com>
escreveu:

**Comment by dirkrombauts** [comment]
Thanks!

**Comment by dirkrombauts** [comment]
I looked into it, and there seems to be a problem with the way Pickles treats `#` comments. It's not limited to the Word output format, the same happens on the other output formats.

The bad news: I'm leaving for a conference tomorrow and won't be back until Wednesday.

The good news: there's a workaround that you can use in the meantime. If you attach the comments to the first line of the scenario rather than the title of the scenario, they will be picked up.

For example this will work:

```
Cenário: Indicador visuais dos movimentos segundo terem pagamentos associados ou não.

#Critérios de aceitação
#Os movimentos que já têm pagamento associado devem ficar com um highligh verde e ter um botão "Ver pagamento".
#Os movimento que não têm pagamento associado devem ficar com um highligh vermelho.
#Um movimento têm um pagamento associado se existir um pagamento com.

Dados os movimentos com os seguintes oooohId:
```

**Comment by StarWars999123** [comment]
We have almost the same issue. Every Scenario is tagged with a #comment before. The last scenario within the feature has allways no visible comment within the Dhtml output.

**Comment by dirkrombauts** [comment]
@StarWars999123 do I understand correctly that the scenarios with a #comment show a visible comment in the Dhtml output, except the last scenario?

**Comment by StarWars999123** [comment]
Yes its correct. Each of our tests has a comment to match a requirement id, e.g.:

```
## RequirementID1....
Scenario: MyExampleScenario
Given I asked
Then I got an answer
```

For each test is the comment visible within the Dhtml after each test. The Firefox DOM shows the comments after each step with the following:

```
<!-- ko if: AfterLastStepComments != null && AfterLastStepComments.length > 0 -->
<span class="comment">
                <!-- ko foreach: AfterLastStepComments -->
                <span data-bind="text: Text">## RequirementID1....</span>
                <br data-bind="visible : $index() != ($parent.length-1)">
                <!-- /ko -->
</span>
<!-- /ko-->
```

However, the comments for the last test are allways shown and are also not part of the generated HTML dom. The dom of the last step of the last test contains here only:

```
<!-- ko if: AfterLastStepComments != null && AfterLastStepComments.length > 0 -->
    <div data-bind="template: { name: 'table-template', data: $data.TableArgument }">
        <div data-bind="if: $data"></div>
    </div>
<!-- /ko-->
```
(Eventhough this DOM part for me looks like this could be a scenario outline as last test: It is not. Its a simple scenario.)

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
