### ISSUE TITLE
(To be closed) Idea: Parse complete solution/folder instead of simple projects

### ISSUE THREAD

**Issue by StarWars999123** [picklesdoc/pickles#494]
Pickles would be really helpful for us, if we could let it run against a complete solution instead of just a project. To group the development results, we do have several projects. Some of them are part of the one, some of the other solution. However, all solutions run against the same software, but have different test targets.
The current approach allows it easily to see, which features are part of the project, but for a complete documentation it would be helpful to browse through all projects and see all available features and the resulting documentation. This could generate a complete software documentation.

**Comment by StarWars999123** [comment]
I realized, that pickles can read a folder recursively. As a result, my ticket was unnecessary and can be closed.

**Comment by dirkrombauts** [comment]
I'm glad you found a way that works for you!

I'll close the issue then :-)
