### ISSUE TITLE
Special characters for Scenario Outline - issue.

### ISSUE THREAD

**Issue by DominikBaran** [picklesdoc/pickles#508]
Hello.
I found an issue for Scenario Outlines and XUnit2 for the special characters.
XUnit2ScenarioOutlineExampleMatcher does not work if there are some special characters in the Scenario Outline name (ex: '(', ')', '-', '_', etc')

**Comment by DominikBaran** [comment]
fix for that issue could be found: https://github.com/picklesdoc/pickles/pull/506

**Comment by DominikBaran** [comment]
[Test.feature.txt](https://github.com/picklesdoc/pickles/files/1709022/Test.feature.txt)

[report.xml.txt](https://github.com/picklesdoc/pickles/files/1709019/report.xml.txt)
@dirkrombauts : Hello Dirk. I have spent some time investigate that issue today. I found that Unit tests covering that functionality work correctly WhenParsingxUnit2ResultsFile -> ThenCanReadResultOfScenarioOutlineWithSpecialCharacters, but real functionality uses in a little bit different flow.
You could find my files attached - feature and report. 

I have implemented workaround for that in the XUnit2ScenarioOutlineExampleMatcher class: https://github.com/picklesdoc/pickles/pull/509

Unfortunately it's not proper fix - so it's your decision if you want to merge it or not.

**Comment by DominikBaran** [comment]
@dirkrombauts : I also found an issue with Unit tests. As you could see in the report above for special characters in XUnit2 report contains special characters and looks like:

  <test name="Verifying that it's not possible to transfer account for ineligible organisation's (deleted/susspended) - test(value: &quot;value2&quot;, value2: &quot;3&quot;, value3: &quot;4&quot;, exampleTags: [])" type="Gemini.Tests.Features.Test.TestFeature" method="VerifyingThatItsNotPossibleToTransferAccountForIneligibleOrganisationsDeletedSusspended_Test" time="0.1358922" result="Pass">
        <traits>
          <trait name="FeatureTitle" value="Test" />
          <trait name="Description" value="Verifying that it's not possible to transfer account for ineligible organisation's (deleted/susspended) - test" />
          <trait name="Category" value="wcc123" />
        </traits>
      </test>

In the Unit test example results file: results-example-xunit2.xml special characters are removed ex:
 <test name="Pickles.TestHarness.xunit2.ScenariosWithSpecialCharactersFeature.ThisIsAScenarioOutlineWithParenthesesHyphenAndComma10_2030_40(result: &quot;pass_1&quot;, exampleTags: [])" type="Pickles.TestHarness.xunit2.ScenariosWithSpecialCharactersFeature" method="ThisIsAScenarioOutlineWithParenthesesHyphenAndComma10_2030_40" time="0.0021581" result="Pass">
        <traits>
          <trait name="FeatureTitle" value="Scenarios With Special Characters" />
          <trait name="Description" value="This is a scenario outline with parentheses, hyphen and comma (10-20, 30-40)" />
        </traits>
      </test>

That's why unit tests for special characters work perfectly fine, but for the examples I have sent before: Matching mechanism does not work correctly.

**Comment by DominikBaran** [comment]
@dirkrombauts : hello Dirk. Any chance to take a look on that ? thanks

**Comment by dirkrombauts** [comment]
Real life is keeping me busy. Things should get quieter from Thursday on ...

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
