### ISSUE TITLE
Scenario Outline Inconclusive

### ISSUE THREAD

**Issue by tmoreno** [picklesdoc/pickles#518]
There is a problem related with the Scenario Outline name.

If it contains latin chars like: ñ, á, é, í, ó, ú the report shows inconclusive, but if I remove those chars from the scenario outline name the report shows the correct test result:

![38687003-f60c79fe-3e75-11e8-902b-ca7dd9872206](https://user-images.githubusercontent.com/1009817/38974886-0041b908-43ac-11e8-87c7-ff24acead678.png)

So, I think that could be an issue related with latin chars in scenario outline names.

**Comment by dirkrombauts** [comment]
@tmoreno could you please check whether this problem still exists in version [2.18.1](https://github.com/picklesdoc/pickles/releases/tag/v2.18.1)? There are some big changes to the name matching in the new version.

**Comment by tmoreno** [comment]
Hi @dirkrombauts,

I've just generated a new report with 2.18.2 version and, works perfectly!

Thank you so much :D

**Comment by dirkrombauts** [comment]
You're welcome!
