### ISSUE TITLE
Scenario Outline Inconclusive when Example contains quotes

### ISSUE THREAD

**Issue by barnabii** [picklesdoc/pickles#521]
Hello 
I've a problem with inconclusive test result (dhtml) when an Example contains quotes " even all steps and  the test result are ok.

Here the example:

Scenario Outline: Generate PLC_Config C-Code with CAP1131.CodeGen.Console
	When I call the CAP1131.CodeGen.Console tool with '<programmArguments>'
	Then the console returns with exit code 0
	And the generated C-Code equals to the reference 

Examples: 
| programmArguments                                                                                 |
| -c "{TestData}\cap1131\CPU831_CBus_Misc" -m "{TestData}\mos\MOS83x_V730.CC6B"                     |

Note: When I remove all the quotes in the feature file the dhtml report is ok (green). 
I've tested it with Pickles Version 2.18.1.
In the nunit3 result file the test is also green.

Thanks and Kind Regards

**Comment by dirkrombauts** [comment]
Did this problem appear in 2.18.1 or is it present in earlier versions as well?

**Comment by DominikBaran** [comment]
hello @barnabii , @dirkrombauts : it could be related to the issue I just reported : https://github.com/picklesdoc/pickles/issues/522

@barnabii: could you please assign nunit report.xml file to check if there is the same issue with " coding ?

**Comment by barnabii** [comment]
hello together, i hope this helps.
thanks!

[pickles_issue_attachment.zip](https://github.com/picklesdoc/pickles/files/1946998/pickles_issue_attachment.zip)

**Comment by dirkrombauts** [comment]
@barnabii is your issue solved?

**Comment by DominikBaran** [comment]
@dirkrombauts : I think it is not - in the nunit report i could see different coding for the '"' character
sometime is &quot; and sometimes it is \&quot
Example line:
<test-case name="Selectron.CAP1131.CodeGen.Acceptance.Features.CAP1131_CodeGen_ConsoleCommandlineFeature.GeneratePLC_ConfigC_CodeWithConsoleFailed(&quot;-c \&quot;Not Available\&quot; -m \&quot;{TestData}\\mos\\MOS83x_V730.CC6B\&quot;&quot;,&quot;'Error: PLC-Config cfi file '*' doesn't exist'&quot;,null)" executed="True" result="Success" success="True" time="0.043" asserts="0" />

I think Pickles does not support both of them in the good way.

**Comment by barnabii** [comment]
Hello together
I have tried with the latest Pikles version 2.20.1 with nunit3 test result file.
Now no more inconclusive test results are shown within the dhtml report.
But every scenario outline example containing a " sign  shows now an empty test result state.
![grafik](https://user-images.githubusercontent.com/7600847/57917496-163bf880-7895-11e9-8183-1b1507824d65.png)

It would be nice if that could be fixed.

**Comment by dirkrombauts** [comment]
Thanks for mentioning this. Matching examples to test results is notoriously brittle. I have very little time to spend on Pickles these days, so unless somebody takes up this issue, it's unlikely to be fixed any time soon.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
