### ISSUE TITLE
PicklesUI from Chocolateley doesn't start

### ISSUE THREAD

**Issue by dirkrombauts** [picklesdoc/pickles#523]
It seems the ControlzEx library is missing from the 2.18.1 package.

**Comment by gep13** [comment]
@dirkrombauts is this in any way related to the discussion that is being held here:

https://gitter.im/chocolatey/chocolatey.org?at=5adf5496270d7d3708ff3faf

I did a fresh install on the picklesui using Chocolatey on a Windows Server 2012 VM, and it worked as expected, but we are getting reports that that installation is working for some people, but then when trying to run the application, it is failing.

**Comment by dirkrombauts** [comment]
Released in version [2.18.2](https://github.com/picklesdoc/pickles/releases/tag/v2.18.2)

**Comment by gep13** [comment]
@dirkrombauts thanks for getting this updated!
