### ISSUE TITLE
CreateTestResults.cmd uses test runners of Visual Studio 2015

### ISSUE THREAD

**Issue by rik-smeets** [picklesdoc/pickles#540]
With VS2017 now well over a year old, it might be time to replace the hardcoded references to the VSTest and MSTest test runners locations in `CreateTestResults.cmd` to their new locations in VS2017.

Small challenge: the install location is now different based on the version of Visual Studio in use, i.e. Community/Enterprise etc.

For example, `vstest.console.exe` can now be found here (when using VS2017 Community):
`%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe`.

**Comment by dirkrombauts** [comment]
I agree that this is a good idea ... some people probably are lucky enough to have only VS2017 :-D

But I don't like the fact of forcing people to have a particular flavour of visual studio. Do you have an idea on how to probe for the existence of a file in a `.cmd` file?

**Comment by rik-smeets** [comment]
I consider myself very lucky indeed ;-).

I think PowerShell is the way to go here. In `.cmd` it can probably be done but I don't think it would be very clean. The current script is ported easily enough to PowerShell, which I could do if you like?

**Comment by dirkrombauts** [comment]
That would be awesome!
