### ISSUE TITLE
VsTestScenarioOutlineExampleMatcher fails to match on examples with comma in the first column

### ISSUE THREAD

**Issue by psoszynski** [picklesdoc/pickles#543]
Adding ".Replace(",", String.Empty)" to:

            var matchValue = exampleValues[0]
                .Replace(" ", string.Empty)
                .Replace(":", string.Empty)
                .Replace("\\", string.Empty)
                .Replace("(", string.Empty)
                .Replace(")", string.Empty)
                .Replace(".", "_")
                .Replace("!", string.Empty)
                .Replace("&", string.Empty)
                .ToUpperInvariant()
                .Replace("Ä", "A")
                .Replace("Ö", "O")
                .Replace("Ü", "U")
                .Replace("ß", "B")
                .Replace("æ", "ae")
                .Replace('ø', 'o')
                .Replace('å', 'a')
                .Replace("Æ", "AE")
                .Replace('Ø', 'O')
                .Replace('Å', 'A');

fixes the problem. Shall I create pull request?

**Comment by rik-smeets** [comment]
This is resolved by my PR as well, which is already opened for review: #542.
