### ISSUE TITLE
Inconclusive marker shown when generating doc without test results

### ISSUE THREAD

**Issue by gasparnagy** [picklesdoc/pickles#545]
I would like to generate the documentation without test results. I don't pass any test result related arg, but the yellow exclamation marks are displayed next to every scenario in DHTML format. 
Is there an easy way to hide these?
I am using v2.19

**Comment by dirkrombauts** [comment]
Hi,

That sounds like a bug :-(

How do the other output formats behave, especially the static HTML format?

**Comment by gasparnagy** [comment]
The problem seems to be only in the dhtml (html and word is fine).

**Comment by dirkrombauts** [comment]
Then it's probably a problem in the templates of the DHTML version. I will probably have time to have a look at it over the weekend.

**Comment by gasparnagy** [comment]
Thx. But if you give me a hint where these templates are, I can also check it. This is not an urgent issue.

**Comment by dirkrombauts** [comment]
The templates (they are knockout-based) are in the Index.html file in the Pickles.BaseDhtmlFiles project.

**Comment by dirkrombauts** [comment]
@gasparnagy could you please try out #546 and check whether it solves your problem?

**Comment by dirkrombauts** [comment]
Released in version [2.20.0](https://github.com/picklesdoc/pickles/releases/tag/v2.20.0).
