### ISSUE TITLE
DHTML report uses warning icon when results aren't used

### ISSUE THREAD

**Issue by AndyLPK247** [picklesdoc/pickles#552]
This is the warning icon: ![image](https://user-images.githubusercontent.com/17988946/46957224-1d7ff700-d065-11e8-8a3d-b778e5a15a70.png)

It appears for all features and scenarios in the DHTML report when no test results are included. This implies that the test results were problematic or inconclusive, rather than not included. It would be helpful if the DHTML report did not include this icon when results were not included (like the HTML report does).

**Comment by dirkrombauts** [comment]
Thanks for telling me about this. Which version of Pickles are you using?

**Comment by AndyLPK247** [comment]
2.19.0

**Comment by dirkrombauts** [comment]
I will release version 2.20.1 soon. When I do, please try gain with that version. There are some relevant changes.

**Comment by dirkrombauts** [comment]
I released version [2.20.1](https://github.com/picklesdoc/pickles/releases/tag/v2.20.1), could you please try that version?

**Comment by AndyLPK247** [comment]
Version 2.20.1 fixes this issue. It's beautiful. Thanks much!
