### ISSUE TITLE
Microsoft.Build.Utilities v3.5 required for Pickles.MSBuild

### ISSUE THREAD

**Issue by gimmi** [picklesdoc/pickles#558]
Hi,

when compiling a project that uses `Pickles.MSBuild` NuGet package, i get the following error:

```
The "Pickles" task could not be loaded from the assembly
C:\Users\dev\Sources\my-project\packages\Pickles.MSBuild.2.16.2\build\..\tools\PicklesDoc.Pickles.MSBuild.Tasks.dll
Could not load file or assembly 'Microsoft.Build.Utilities.v3.5, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
The system cannot find the file specified.
Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

This seems to be related to the fact that i don't have __legacy__ versions of .NET runtime installed on the machine.

**Comment by dirkrombauts** [comment]
What exactly do you mean by "legacy" version of .NET runtime?

Also: from the error message it seems you are using quite an old version of Pickles (2.16.2) - could you please try to use the latest version and see if it works better?

**Comment by gimmi** [comment]
> What exactly do you mean by "legacy" version of .NET runtime?

I suppose that what's needed is the ".NET Framework 3.5 (includes .NET 2.0 and 3.0)" Windows feature:

![image](https://user-images.githubusercontent.com/6589/47656244-0118aa00-db8f-11e8-93d8-c9b26c864b62.png)

> seems you are using quite an old version of Pickles (2.16.2)

Ok, will try

**Comment by shahzad285** [comment]
HI @gimmi did the above solution resolve the issue

**Comment by gimmi** [comment]
Hi @shahzad285 

sorry, but I've moved away from the project that uses that old pickles version, and I have not a quick way to test it.

Will close the issue for now, thanks for support.

**Comment by srinivas2901** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4062	The "Pickles" task could not be loaded from the assembly C:\Users\Srinu\.nuget\packages\pickles.msbuild\2.21.0\build\..\tools\PicklesDoc.Pickles.MSBuild.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v3.5, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	My.Automation.Demo.Tests	C:\Users\Srinu\.nuget\packages\pickles.msbuild\2.21.0\build\Pickles.MSBuild.targets	12

**Comment by srinivas2901** [comment]
> Severity Code Description Project File Line Suppression State
> Error MSB4062 The "Pickles" task could not be loaded from the assembly C:\Users\Srinu.nuget\packages\pickles.msbuild\2.21.0\build..\tools\PicklesDoc.Pickles.MSBuild.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v3.5, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. My.Automation.Demo.Tests C:\Users\Srinu.nuget\packages\pickles.msbuild\2.21.0\build\Pickles.MSBuild.targets 12

Any one please help me in resolving this issues. What is reason of the error.?

**Comment by srinivas2901** [comment]
> Severity Code Description Project File Line Suppression State
> Error MSB4062 The "Pickles" task could not be loaded from the assembly C:\Users\Srinu\.nuget\packages\pickles.msbuild\2.21.0\build..\tools\PicklesDoc.Pickles.MSBuild.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v3.5, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. My.Automation.Demo.Tests C:\Users\Srinu\.nuget\packages\pickles.msbuild\2.21.0\build\Pickles.MSBuild.targets 12

Any one please help me in resolving this issues. What is reason of the error.?

**Comment by srinivas2901** [comment]
Severity Code Description Project File Line Suppression State
 Error MSB4062 The "Pickles" task could not be loaded from the assembly C:\Users\Srinu\ .nuget\packages\pickles.msbuild\2.21.0\build..\tools\PicklesDoc.Pickles.MSBuild.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v3.5, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. My.Automation.Demo.Tests  C:\Users\Srinu\
.nuget\packages\pickles.msbuild\2.21.0\build\Pickles.MSBuild.targets 12

**Any one please help me in resolving this issues. What is reason of the error.?**
