### ISSUE TITLE
Invalid comparison 

### ISSUE THREAD

**Issue by matthew-p** [picklesdoc/pickles#560]
Is line 46 here actually the intended implementation? 

"if: (!WasExecuted && WasExecuted)"

https://github.com/picklesdoc/pickles/commit/f078a8ac2f7b76ab04b3d301d9184d7e5d105864#diff-63def25e4324a85e098e45f45fbbc241

**Comment by dirkrombauts** [comment]
No ... that should probably be `(!WasExecuted && WasProvided)` ...

**Comment by dirkrombauts** [comment]
Could you make a pull request with a fix? Many thanks!
