### ISSUE TITLE
Cannot generate documentation under Windows if pickles is installed in a different drive than the features location

### ISSUE THREAD

**Issue by zadigus** [picklesdoc/pickles#561]
Hi,

I wanted to give pickles a try and I already found a problem. 

Given

* my features are located under d:\webdev\spec\features
* my pickles installation is under c:\ProgramData\chocolatey\bin\pickles.exe

When I run 

    c:\ProgramData\chocolatey\bin\pickles.exe --feature-directory="d:\webdev\spec\features" --output-directory="d:\webdev\spec\documentation" --system-under-test-name=my-project --system-under-test-version=0.0.0 --language=fr --df=html
 
Then the command returns, the documentation folder is created but is empty. I don't even get an error message.    

Now, I tried to copy my features folder into the c:\ProgramData\chocolatey\bin\ folder where I then called

    pickles.exe --feature-directory=".\features" --output-directory=".\documentation" --system-under-test-name=my-project --system-under-test-version=0.0.0 --language=fr --df=html

This worked. 

Therefore, it seems like pickles doesn't deal well with different hard drives. How can I fix that (except by copying all my features from the one hard drive to the other of course)? Is there an option I haven't seen yet?

Cheers

**Comment by dirkrombauts** [comment]
Thanks ... that looks unexpected. What does it look like with the second version?

BTW: under windows, "clear" is called "cls"

**Comment by zadigus** [comment]
In fact, I got it working now when I run pickles from drive c:\ on a spec located on drive d:\. Here's the console output:

![image](https://user-images.githubusercontent.com/8761254/48055980-2621a400-e1b1-11e8-9618-e8eac64e4328.png)

Still no summary though and also the recursive scanning doesn't work, that's why my commands in the above messages were not working. My folder structure is like this:

d:\webdev\spec\features
  - folder Authentication
  - folder Producer
    - folder History
    - folder ProductsManagement
    - folder Profile
      - file EditProfile.feature
      - file PreviewProfile.feature
      - file SUMMARY.md
    - file AddPicture.feature
    - file ProducerMustLogin.feature
    - SUMMARY.md
  - file SUMMARY.md

Is such a folder structure incompatible with pickles?

**Comment by dirkrombauts** [comment]
It should be compatible ... are there perhaps any syntax errors in your feature files?

**Comment by zadigus** [comment]
How is pickles dealing with empty feature files or files with comments only? Because I noticed that I have such files in that huge spec.

**Comment by dirkrombauts** [comment]
Pickles doesn't like them at all. It throws an exception. The exception message could be improved to mention the file that causes the error. And In a next step, Pickles could collect all the errors, continue processing the correct files and dumping a combined error message at the end.

**Comment by zadigus** [comment]
Interesting. I get no exception at all. Is that logged somewhere?

**Comment by zadigus** [comment]
> That should work, yes.

I'll give it a shot a bit later today then and keep you informed.

**Comment by zadigus** [comment]
So, as far as I can tell, adding a tag to all empty files or files containing only comments fixed the problem of not generating the documentation (but not that of not producing the summary output you told me about). I don't need to add the tag to the list of excluded tags. The minimum requirement seems to be that the feature files contain at least a tag or a Feature.
