### ISSUE TITLE
Some types of tables do not render appropriately in HTML

### ISSUE THREAD

**Issue by zadigus** [picklesdoc/pickles#562]
Hi,
According to "The Cucumber Book", tables of the following kind are perfectly valid:

![image](https://user-images.githubusercontent.com/8761254/48114017-a1409400-e25d-11e8-8a70-23036af94ca1.png)

In the first case, the headers are vertical and in the second case, they are absent.

When I, however, generate the corresponding pickles documentation, I always get the first row highlighted in bold. In the first case depicted above, I would expect the first column to be highlighted in bold whereas I would expect no highlighting in the second. 

Now, I perfectly understand that it is not possible to decide in which case we are when we read those tables when it comes to generate HTML documentation (or the other kinds too). Is there a way for me to specify this in my feature file somehow?
Cheers

**Comment by dirkrombauts** [comment]
Hi,
No, there’s no way to indicate this in the feature file. I usually use column headers like “property” and “value” in this case. With the added benefit that the SpecFlow automation layer recognizes this to populate objects from a table.

**Comment by zadigus** [comment]
Ok thanks.

**Comment by zadigus** [comment]
By the way, your library is very great, I like it very much.

**Comment by dirkrombauts** [comment]
Thank you!
