### ISSUE TITLE
Path issues on MacOS

### ISSUE THREAD

**Issue by vikaci** [picklesdoc/pickles#569]
Hi, 

I have macOS 10.14 and run Pickles.exe under Mono. 

When I run pickles and specify exactly the folder with features (e.g. Acceptance/Smoke/features) - everything is ok.

But when I want to run pickles for the whole Acceptance directory I get this error:

`Pickles did not complete successfully Object reference not set to an instance of an object`

**Comment by vikaci** [comment]
Thanks for the fats reply @dirkrombauts !
Is there another way that I can get my .html file to be generated with a folder/subfolder structure? Otherwise I have a separate .html for each of my features folders :(

**Comment by dirkrombauts** [comment]
What is your directory structure exactly?

**Comment by vikaci** [comment]
Would look like this:
/project_folder
/feature_1/files.feature
/feature_2/files.feature
/feature_3/files.feature

basically a project folder with subfolders for each feature, in which the feature files are nested.

Thx!

**Comment by dirkrombauts** [comment]
I'm assuming that the structure is

```
/project_folder/feature_1/files.feature
/project_folder/feature_2/files.feature
/project_folder/feature_3/files.feature
```

If you point Pickles to /project_folder, it should generate an index.html at the level of project_folder. It's important that project_folder and its subfolders is dedicated to `.feature` files (Markdown files and images are OK as well). Don't mix it with code files and other artifacts.

But as I said, Pickles does not officially supported on MacOS. So I cannot guarantee that it will work on MacOS even if you set everything correctly.

**Comment by vikaci** [comment]
Thx. Found the issue now. I had a folder where the feature file was empty (blank) 
Got my folder structure. Can confirm that it works nicely on macOS :)

**Comment by dirkrombauts** [comment]
I'm glad that you got it working for you :-)
