### ISSUE TITLE
cannot serialize '_io.BufferedReader' object

### ISSUE THREAD

**Issue by Pepsipu** [picklesdoc/pickles#572]
I'm trying to pickle a large class as a string to store into a database, but i get this error.
Could anyone shed some light on what this error is stating?

**Comment by dirkrombauts** [comment]
Hi,

Can you give us a bit more information: where do you see this error? When exactly does it happen? Which version of Pickles are you using, on which platform?

**Comment by dirkrombauts** [comment]
I'm closing this issue because the original poster did not reply after two weeks. Additionally, from the title it sounds like something python-related, and was probably posted on the wrong board.
