### ISSUE TITLE
import pickle

### ISSUE THREAD

**Issue by rutujar** [picklesdoc/pickles#573]
How to install pickle  in Python3 for ubuntu 16. 04?

**Comment by dirkrombauts** [comment]
Pickles is not supported on Ubuntu or Linux in general. It usually works pretty well when using Mono on Linux. Python is not relevant for Pickles.

**Comment by rutujar** [comment]
@dirkrombauts i need ur help for my work

* part of the code
import pickle
charModel = cPickle.loads(open(args["char_classifier"]).read())
digitModel = cPickle.loads(open(args["digit_classifier"]).read())

* error
charModel = cPickle.loads(open(args["char_classifier"]).read())
NameError: name 'cPickle' is not defined

how to resolve this issue help needed.

**Comment by dirkrombauts** [comment]
Sorry mate, you’re at the wrong place. Pickles is a stand-alone Windows program, not a Python library.

Since I have no experience with Python at all, I cannot help you.

**Comment by rutujar** [comment]
Ok
