### ISSUE TITLE
Latest version fails silently and doesn't generate anything

### ISSUE THREAD

**Issue by janissimsons** [picklesdoc/pickles#575]
Hi,
I just updated to the latest version (2.20.1.0) and when I generate report from command line, just as I did before, it fails silently (no errors, no output at all) and nothing is created in the output folder.

Command I use:
`pickles --feature-directory="C:\Code\repos\projectName\Tests.Dir\Features" --output-directory="C:\Code\repos\projectName\docs" --enableComments=false --language=en --documentation-format=dhtml`

When I was on previous version, I think it was 2.19.. or something, then this command worked without issues.

**Comment by janissimsons** [comment]
I tried running the tool from VS Package Manager Console, then it output a single line of error:
`Pickles did not complete successfully Object reference not set to an instance of an object.`

There I used this command:
`.\packages\Pickles.CommandLine.2.20.1\tools\pickles.exe --feature-directory=.\Tests.Dir\Features --output-directory=.\docs`

**Comment by janissimsons** [comment]
I think I found the issue, I had a feature file which was completely commented out (every single line). I tried deleting that feature and running Pickles again, and then the report was generated.
@dirkrombauts could you add a fix for these kinds of situations? Ignoring features that aren't formatted correctly and warning user about it.

Thanks!

**Comment by dirkrombauts** [comment]
@janissimsons I agree that it would be much better if Pickles would not fail silently in these cases.

My Pickles time is currently extremely limited, so your best bet to have this fast is to implement it yourself (including unit tests), and send me a pull request. Thanks!

**Comment by dirkrombauts** [comment]
I'm closing this issue since the behavior is not specific to the latest version - it's actually a known issue.
