### ISSUE TITLE
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'PicklesDoc.Pickles.TestFrameworks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by lobeu** [picklesdoc/pickles#581]
Hi there,

I've been using pickles for more than a year on my project and it's great!

However for some reason it stopped working today. We changed nothing and suddenly when running the command in commandline the following error is thrown:

![image](https://user-images.githubusercontent.com/34190689/78336128-246b3400-758f-11ea-9196-3b76f2e584f6.png)

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'PicklesDoc.Pickles.TestFrameworks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at PicklesDoc.Pickles.PicklesModule.Load(ContainerBuilder builder)
   at Autofac.Module.Configure(IComponentRegistry componentRegistry)
   at Autofac.ContainerBuilder.Build(IComponentRegistry componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at PicklesDoc.Pickles.CommandLine.Program.Main(String[] args)

I've been looking into why this is suddenly missing but I really have no clue.

Could someone help?

Thx in advance.

Grts,

Louis

**Comment by dirkrombauts** [comment]
Hi,

This is just a wild guess, but did you perhaps upgrade SpecRun?

**Comment by taizoon** [comment]
I ran into the same issue as well. Turns out that the `PicklesDoc.Pickles.TestFrameworks.dll` was picked up as a Trojan. I removed that package from our code repo for now

**Comment by dirkrombauts** [comment]
That's interesting. Did you see any indication why it might have been considered a Trojan?

**Comment by taizoon** [comment]
not really.. another member on team as well saw the same issue. I suspect that's preventing the dll from being loaded.

**Comment by taizoon** [comment]
This is the reason from reported by the Anti-Virus agent - **Trojan HEUR:Trojan.MSIL.Crypt.gen**

**Comment by hpcergar** [comment]
Hi, I am experiencing the very same problem. Is there any workaround? @taizoon did you find a solution or was just avoiding pickles for now? I have tried excluding this file from the antivirus but, no luck, I have not enough rights in company's laptop. 

Any ideas?

**Comment by taizoon** [comment]
@hpcergar we disabled pickle generation for now. Our IT admin is also looking to see if there's any more info on it, but no luck so far.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
