### ISSUE TITLE
Pickles generates extra columns for scenario tables in HTML mode

### ISSUE THREAD

**Issue by boc-tothefuture** [picklesdoc/pickles#598]
For example, see this rendered HTML: https://boc-tothefuture.github.io/openhab-jruby/pickles/changed.html

Generated from this Gherkin file: https://github.com/boc-tothefuture/openhab-jruby/blob/main/features/changed.feature

**Comment by boc-tothefuture** [comment]
@ericcallsynx - Is there anything I can do to prevent this?

**Comment by ericcallsynx** [comment]
It doesn't show up in the dhtml version but that probably doesn't help you. Looking at the code I don't see anything obvious that is creating the issue but I will try to address it soon.

**Comment by ericcallsynx** [comment]
released in version 2.21.1

**Comment by ericcallsynx** [comment]
@boc-tothefuture I've pushed a new version that should fix this issue. This is my first go at the build and release process for pickles so let me know if you find anything amiss!

**Comment by boc-tothefuture** [comment]
Thanks, I will see if it gets pulled in by my build process which is just using choco.
