### ISSUE TITLE
Cannot upgrade .Net 4.8 project to 3.0.1

### ISSUE THREAD

**Issue by ccbristo** [picklesdoc/pickles#629]
When I try to update from pickles 2.21.1 to 3.0.1 in my .Net 4.8 project, I get this error:

Package 'Pickles.CommandLine 3.0.1' has a package type 'DotnetTool' that is not supported by project

It is my understanding that pickles 3.x still supports .Net framework 4.8 (i.e. I don't need to be on .Net Core/.Net 5) to use it.

Is this an error in the Nuget package, am I doing something wrong, or is this expected?

**Comment by ericcmmi** [comment]
Pickles 3.0.1 is written to the dotnet standard so it can be compiled to core or framework but the Nuget package is compiled as dotnet core. I need to do some research how to support Nuget packages for both framework and dotnet core. I will try to get this done quickly.
