### ISSUE TITLE
Pickles generates upercase status entries in cucumber.json instead of all lower case

### ISSUE THREAD

**Issue by remogloor** [picklesdoc/pickles#640]
Pickles generates upercase status entries e.g. "status": "Passed"
According to the  cucumber.json schema it should be lower case "status": "passed"
See [https://github.com/cucumber/cucumber-json-converter](https://github.com/cucumber/cucumber-json-converter)

Fixed by #639

**Comment by ericcmmi** [comment]
released with 4.0.3
