### ISSUE TITLE
Could the GUI generate the equivalent PowerShell or Windows Console command line?

### ISSUE THREAD

**Issue by roundand** [picklesdoc/pickles#90]
All my SpecFlow tests are run nightly by TeamCity. It would be really helpful for the GUI to have an automation-friendly mode which would generate a PS1 command line which could then be pasted into a TeamCity Step.

The workflow would be something like
- [ ] use GUI to tune and check Pickles settings
- [ ] use GUI to generate PowerShell (or Windows Console) command line
- [ ] paste command line into appropriate TeamCity Step
- [ ] run overnight, every night, for improved documentation
- [ ] bundle Pickles output into deployment along with release notes

**Comment by roundand** [comment]
Glad to see this is still live!

**Comment by dirkrombauts** [comment]
:-)
I'm sorry this is taking so long. I'm basically the only person maintaining Pickles and I was ill for a long time last year. Things are getting better, though.

**Comment by roundand** [comment]
Glad you're better, Dirk - that's the important thing :)

**Comment by magicmonty** [comment]
I will give it a try

**Comment by roundand** [comment]
That's so great, thank you both!

**Comment by dirkrombauts** [comment]
Released in version [2.20.0](https://github.com/picklesdoc/pickles/releases/tag/v2.20.0).
